import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, FileCheck2 } from "lucide-react";
import { generatePacketAction } from "@/app/actions/packets";
import { db } from "@/lib/db";
import { canAccessCase, requireRole } from "@/lib/auth/session";
import { CaseHeader } from "@/features/cases/case-header";
import { SectionHeading } from "@/components/section-heading";
import { StatusBadge } from "@/components/status-badge";
import { SubmitButton } from "@/components/submit-button";
import { formatDate } from "@/lib/format";

export default async function ReviewSummaryBuilderPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireRole(["CASEWORKER"]); const { id } = await params; if (!(await canAccessCase(user, id))) notFound();
  const clientCase = await db.clientCase.findUnique({ where: { id }, include: { selectedProgram: true, packets: { orderBy: { version: "desc" } }, documents: true, householdMembers: true } });
  if (!clientCase) notFound(); const action = generatePacketAction.bind(null, id); const ready = Boolean(clientCase.selectedProgram && clientCase.legalName && clientCase.currentLivingSituation);
  return <div><CaseHeader clientCase={clientCase} /><section className="mt-10"><SectionHeading title="Internal review summary" description="Create an immutable case snapshot for reviewer decisions. This summary is separate from the completed housing application." /><div className="mt-5 grid border-y md:grid-cols-3 md:divide-x"><Check label="Client record" value={clientCase.legalName ? "Ready" : "Missing legal name"} ready={Boolean(clientCase.legalName)} /><Check label="Selected program" value={clientCase.selectedProgram?.name ?? "Not selected"} ready={Boolean(clientCase.selectedProgram)} /><Check label="Source documents" value={`${clientCase.documents.length} uploaded`} ready={clientCase.documents.length > 0} /></div><div className="mt-6 rounded-lg border bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-5"><div><h3 className="text-lg font-semibold">Generate review summary version {(clientCase.packets[0]?.version ?? 0) + 1}</h3><p className="mt-1 max-w-2xl text-sm text-muted-foreground">The snapshot records client facts, requirements, reviewed document fields, missing information, and staff review items without changing the application draft.</p></div><form action={action}><SubmitButton disabled={!ready} pendingLabel="Generating snapshot…"><FileCheck2 /> Generate review summary</SubmitButton></form></div>{!ready && <p role="alert" className="mt-4 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Add a current living situation and select a program before generating a review summary.</p>}</div></section><section className="mt-12"><SectionHeading title="Review summary versions" /><div className="mt-5 divide-y border-y">{clientCase.packets.length ? clientCase.packets.map((packet) => <Link data-row-link key={packet.id} href={`/packets/${packet.id}`} className="grid items-center gap-4 rounded-md px-3 py-4 sm:grid-cols-[120px_1fr_170px_auto]"><div className="font-medium text-primary">Version {packet.version}</div><div><div>{packet.referenceNumber}</div><div className="text-xs text-muted-foreground">Generated {formatDate(packet.generatedAt)}</div></div><StatusBadge status={packet.status} /><ArrowRight className="h-4 w-4" /></Link>) : <div className="p-8 text-center text-sm text-muted-foreground">No internal review summary has been generated for this case.</div>}</div></section></div>;
}
function Check({ label, value, ready }: { label: string; value: string; ready: boolean }) { return <div className="p-5"><div className="text-xs font-medium text-muted-foreground">{label}</div><div className="mt-2 font-medium">{value}</div><div className={`mt-5 text-xs font-medium ${ready ? "text-emerald-700" : "text-amber-700"}`}>{ready ? "Available" : "Needs attention"}</div></div>; }
