type ScopeFactory = (organizationId: string) => Record<string, unknown>;

export const tenantScopeByModel: Record<string, ScopeFactory> = {
  Organization: (organizationId) => ({ id: organizationId }),
  User: (organizationId) => ({ organizationId }),
  MfaChallenge: (organizationId) => ({ user: { organizationId } }),
  AuthSession: (organizationId) => ({ organizationId }),
  PasswordResetToken: (organizationId) => ({ user: { organizationId } }),
  ClientCase: (organizationId) => ({ organizationId }),
  HouseholdMember: (organizationId) => ({ clientCase: { organizationId } }),
  IncomeRecord: (organizationId) => ({ clientCase: { organizationId } }),
  HousingProgram: (organizationId) => ({ organizationId }),
  ProgramRequirement: (organizationId) => ({ housingProgram: { organizationId } }),
  UploadedDocument: (organizationId) => ({ clientCase: { organizationId } }),
  ApplicationTemplate: (organizationId) => ({ housingProgram: { organizationId } }),
  ApplicationTemplateField: (organizationId) => ({ template: { housingProgram: { organizationId } } }),
  ApplicationDraft: (organizationId) => ({ clientCase: { organizationId } }),
  ApplicationSignature: (organizationId) => ({ draft: { clientCase: { organizationId } } }),
  ConsentRecord: (organizationId) => ({ clientCase: { organizationId } }),
  SubmissionDestination: (organizationId) => ({ housingProgram: { organizationId } }),
  ApplicationSubmission: (organizationId) => ({ draft: { clientCase: { organizationId } } }),
  ApplicationDraftField: (organizationId) => ({ draft: { clientCase: { organizationId } } }),
  ApplicationDraftDocument: (organizationId) => ({ draft: { clientCase: { organizationId } } }),
  ExtractedField: (organizationId) => ({ uploadedDocument: { clientCase: { organizationId } } }),
  ExtractedFieldRevision: (organizationId) => ({ extractedField: { uploadedDocument: { clientCase: { organizationId } } } }),
  AgencyFieldDefinition: (organizationId) => ({ organizationId }),
  CaseFieldValue: (organizationId) => ({ clientCase: { organizationId } }),
  WorkflowDefinition: (organizationId) => ({ organizationId }),
  DocumentProfile: (organizationId) => ({ organizationId }),
  ApplicationPacket: (organizationId) => ({ clientCase: { organizationId } }),
  PacketField: (organizationId) => ({ packet: { clientCase: { organizationId } } }),
  ReviewNote: (organizationId) => ({ packet: { clientCase: { organizationId } } }),
  RequirementOverride: (organizationId) => ({ packet: { clientCase: { organizationId } } }),
  AuditEvent: (organizationId) => ({ organizationId }),
  DataLifecycleRequest: (organizationId) => ({ organizationId }),
  BackgroundJob: (organizationId) => ({ organizationId }),
  OrganizationSetupSection: (organizationId) => ({ organizationId }),
  SecureDownload: (organizationId) => ({ organizationId }),
};

export const directTenantModels = new Set([
  "AuthSession",
  "AuditEvent",
  "DataLifecycleRequest",
  "BackgroundJob",
  "ClientCase",
  "HousingProgram",
  "User",
  "OrganizationSetupSection",
  "SecureDownload",
]);

export const tenantParentsByModel: Record<string, { model: string; foreignKey: string }[]> = {
  MfaChallenge: [{ model: "User", foreignKey: "userId" }],
  AuthSession: [{ model: "User", foreignKey: "userId" }],
  PasswordResetToken: [{ model: "User", foreignKey: "userId" }],
  ClientCase: [{ model: "User", foreignKey: "assignedCaseworkerId" }, { model: "HousingProgram", foreignKey: "selectedProgramId" }],
  HouseholdMember: [{ model: "ClientCase", foreignKey: "clientCaseId" }],
  IncomeRecord: [{ model: "ClientCase", foreignKey: "clientCaseId" }, { model: "HouseholdMember", foreignKey: "householdMemberId" }],
  ProgramRequirement: [{ model: "HousingProgram", foreignKey: "housingProgramId" }],
  UploadedDocument: [{ model: "ClientCase", foreignKey: "clientCaseId" }, { model: "User", foreignKey: "uploadedById" }],
  ApplicationTemplate: [{ model: "HousingProgram", foreignKey: "housingProgramId" }, { model: "ApplicationTemplate", foreignKey: "supersedesTemplateId" }],
  ApplicationTemplateField: [{ model: "ApplicationTemplate", foreignKey: "templateId" }],
  ApplicationDraft: [{ model: "ClientCase", foreignKey: "clientCaseId" }, { model: "ApplicationTemplate", foreignKey: "templateId" }, { model: "User", foreignKey: "createdById" }],
  ApplicationSignature: [{ model: "ApplicationDraft", foreignKey: "draftId" }, { model: "User", foreignKey: "capturedById" }],
  ConsentRecord: [{ model: "ClientCase", foreignKey: "clientCaseId" }, { model: "ApplicationDraft", foreignKey: "draftId" }, { model: "User", foreignKey: "recordedById" }],
  SubmissionDestination: [{ model: "HousingProgram", foreignKey: "housingProgramId" }],
  ApplicationSubmission: [{ model: "ApplicationDraft", foreignKey: "draftId" }, { model: "SubmissionDestination", foreignKey: "destinationId" }],
  ApplicationDraftField: [{ model: "ApplicationDraft", foreignKey: "draftId" }, { model: "ApplicationTemplateField", foreignKey: "templateFieldId" }, { model: "User", foreignKey: "answeredById" }],
  ApplicationDraftDocument: [{ model: "ApplicationDraft", foreignKey: "draftId" }, { model: "UploadedDocument", foreignKey: "uploadedDocumentId" }],
  ExtractedField: [{ model: "UploadedDocument", foreignKey: "uploadedDocumentId" }, { model: "User", foreignKey: "reviewerId" }],
  ExtractedFieldRevision: [{ model: "ExtractedField", foreignKey: "extractedFieldId" }, { model: "User", foreignKey: "reviewerId" }],
  AgencyFieldDefinition: [{ model: "Organization", foreignKey: "organizationId" }],
  CaseFieldValue: [{ model: "ClientCase", foreignKey: "clientCaseId" }, { model: "AgencyFieldDefinition", foreignKey: "definitionId" }],
  WorkflowDefinition: [{ model: "Organization", foreignKey: "organizationId" }],
  DocumentProfile: [{ model: "Organization", foreignKey: "organizationId" }],
  ApplicationPacket: [{ model: "ClientCase", foreignKey: "clientCaseId" }, { model: "HousingProgram", foreignKey: "housingProgramId" }, { model: "User", foreignKey: "approvedById" }],
  PacketField: [{ model: "ApplicationPacket", foreignKey: "packetId" }, { model: "User", foreignKey: "reviewerId" }],
  ReviewNote: [{ model: "ApplicationPacket", foreignKey: "packetId" }, { model: "User", foreignKey: "authorId" }],
  RequirementOverride: [{ model: "ApplicationPacket", foreignKey: "packetId" }, { model: "User", foreignKey: "reviewerId" }],
  AuditEvent: [{ model: "User", foreignKey: "userId" }, { model: "ClientCase", foreignKey: "clientCaseId" }],
  DataLifecycleRequest: [{ model: "ClientCase", foreignKey: "clientCaseId" }, { model: "User", foreignKey: "requestedById" }, { model: "User", foreignKey: "approvedById" }],
  OrganizationSetupSection: [{ model: "User", foreignKey: "updatedById" }],
  SecureDownload: [{ model: "User", foreignKey: "createdById" }],
};
