import Image from "next/image";
import { generateURI } from "otplib";
import QRCode from "qrcode";
import { beginMfaSetupAction, confirmMfaSetupAction, disableMfaAction } from "@/app/actions/auth";
import { SubmitButton } from "@/components/submit-button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { activateOrganizationContext, requireUser } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { decryptText } from "@/lib/security/encryption";

export default async function AccountSecurityPage({ searchParams }: { searchParams: Promise<{ setup?: string; enabled?: string; error?: string }> }) {
  const user = activateOrganizationContext(await requireUser({ allowMfaEnrollment: true })); const params = await searchParams; const record = await db.user.findUniqueOrThrow({ where: { id: user.id } }); const secret = record.mfaSecretEncrypted ? decryptText(record.mfaSecretEncrypted) : null; const recoveryCodes = record.mfaRecoveryCodesEncrypted ? JSON.parse(decryptText(record.mfaRecoveryCodesEncrypted)) as string[] : []; const qr = secret ? await QRCode.toDataURL(generateURI({ issuer: "Housing Application Packet Builder", label: user.email, secret })) : null;
  return <div className="mx-auto max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-primary">Account security</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.03em]">Multi-factor authentication</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Require a time-based code after your password. Recovery codes are single-use and should be stored securely.</p>{params.error && <div role="alert" className="mt-6 border border-red-300 bg-red-50 p-4 text-sm text-red-800">{params.error}</div>}{record.mfaEnabled ? <section className="mt-8 border bg-white p-6"><h2 className="text-lg font-semibold">MFA is enabled</h2><p className="mt-2 text-sm text-muted-foreground">{recoveryCodes.length} recovery codes remain.</p><details className="mt-5 border bg-secondary p-4"><summary className="cursor-pointer font-medium">Show recovery codes</summary><ul className="mt-4 grid gap-2 font-mono text-sm sm:grid-cols-2">{recoveryCodes.map((code) => <li key={code}>{code}</li>)}</ul></details><form action={disableMfaAction} className="mt-6 flex flex-wrap items-end gap-3"><div className="space-y-2"><Label htmlFor="disable-code">Current authenticator code</Label><Input id="disable-code" name="code" inputMode="numeric" autoComplete="one-time-code" required /></div><SubmitButton variant="destructive" pendingLabel="Disabling…">Disable MFA and sign out</SubmitButton></form></section> : params.setup && secret && qr ? <section className="mt-8 grid gap-6 border bg-white p-6 sm:grid-cols-[180px_1fr]"><Image src={qr} width={180} height={180} alt="Authenticator setup QR code" unoptimized /><div><h2 className="text-lg font-semibold">Scan and verify</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Scan the QR code with an authenticator app, then enter the six-digit code it shows.</p><p className="mt-3 break-all border bg-secondary p-3 font-mono text-xs">{secret}</p><form action={confirmMfaSetupAction} className="mt-5 flex items-end gap-3"><div className="space-y-2"><Label htmlFor="confirm-code">Verification code</Label><Input id="confirm-code" name="code" inputMode="numeric" autoComplete="one-time-code" required /></div><SubmitButton pendingLabel="Enabling…">Enable MFA</SubmitButton></form></div></section> : <form action={beginMfaSetupAction} className="mt-8 border bg-white p-6"><h2 className="text-lg font-semibold">Protect this account</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Setup takes about one minute and works with standard TOTP authenticator apps.</p><div className="mt-5"><SubmitButton pendingLabel="Starting…">Set up MFA</SubmitButton></div></form>}</div>;
}
