import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CheckCircle2, CircleAlert, RefreshCw } from "lucide-react";
import { refreshApplicationDraftAction } from "@/app/actions/applications";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/status-badge";
import { SubmitButton } from "@/components/submit-button";
import { calculateDraftReadiness } from "@/lib/applications/mapping";
import { canAccessCase, requireUser } from "@/lib/auth/session";
import { db } from "@/lib/db";

export default async function PrepareApplicationPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string }> }) {
  const user = await requireUser(); const { id } = await params; const { error } = await searchParams;
  const draft = await db.applicationDraft.findUnique({ where: { id }, include: { clientCase: true, template: { include: { housingProgram: true } }, fields: { include: { templateField: true }, orderBy: { templateField: { displayOrder: "asc" } } } } });
  if (!draft || !(await canAccessCase(user, draft.clientCaseId))) notFound();
  const readiness = calculateDraftReadiness(draft.fields.map((field) => ({ required: field.templateField.required, fieldType: field.templateField.fieldType, finalValue: field.finalValue, reviewState: field.reviewState, validationState: field.validationState })));
  const attention = draft.fields.filter((field) => ["NEEDS_ANSWER", "CONFLICT", "EXPIRED", "AWAITING_CONFIRMATION"].includes(field.reviewState) || ["MISSING", "INVALID", "CONFLICT", "EXPIRED"].includes(field.validationState));
  const completed = draft.fields.filter((field) => field.reviewState === "AUTOMATICALLY_COMPLETED" || field.reviewState === "CONFIRMED");
  return <div><div className="flex flex-wrap items-start justify-between gap-5 border-b pb-6"><div><Link href={`/cases/${draft.clientCaseId}`} className="text-sm font-medium text-primary underline underline-offset-4">Back to case</Link><p className="mt-5 text-xs font-semibold uppercase tracking-[0.08em] text-primary">Prepare application</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.03em]">{draft.template.name}</h1><p className="mt-2 text-sm text-muted-foreground">{draft.clientCase.legalName} · {draft.template.housingProgram.name} · Template version {draft.templateVersion}</p></div><div className="flex flex-wrap items-center gap-2"><StatusBadge status={draft.status} />{user.role === "CASEWORKER" && <form action={refreshApplicationDraftAction.bind(null, id)}><SubmitButton variant="outline" pendingLabel="Refreshing…"><RefreshCw /> Refresh from profile</SubmitButton></form>}</div></div>
    {error && <div role="alert" className="mt-5 rounded-md border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900">{error}</div>}
    <div className="mt-6 grid border-y sm:grid-cols-3 sm:divide-x"><Metric label="Application fields" value={readiness.totalCount} /><Metric label="Automatically completed" value={completed.filter((field) => field.populationMethod !== "STAFF_ENTRY").length} good /><Metric label="Needs attention" value={attention.length} attention={attention.length > 0} /></div>
    <section className="mt-9"><div className="flex flex-wrap items-end justify-between gap-4 border-b pb-4"><div><h2 className="text-xl font-semibold">Needs attention</h2><p className="mt-1 text-sm text-muted-foreground">Answer only what could not be completed reliably from reviewed information.</p></div>{attention.length > 0 && <Button asChild><Link href={`/applications/${id}/questions`}>Complete remaining questions <ArrowRight /></Link></Button>}</div>{attention.length ? <div className="divide-y">{attention.map((field) => <FieldRow key={field.id} field={field} />)}</div> : <div className="flex items-center gap-3 border-b py-6 text-sm text-emerald-800"><CheckCircle2 className="h-5 w-5" />All required application fields are resolved.</div>}</section>
    <section className="mt-9"><details className="group"><summary className="flex cursor-pointer list-none items-center justify-between border-b pb-4"><div><h2 className="text-xl font-semibold">Automatically completed</h2><p className="mt-1 text-sm text-muted-foreground">{completed.length} fields mapped from reviewed information or calculated values.</p></div><span className="text-sm font-medium text-primary group-open:hidden">Show fields</span><span className="hidden text-sm font-medium text-primary group-open:inline">Hide fields</span></summary><div className="divide-y">{completed.map((field) => <FieldRow key={field.id} field={field} />)}</div></details></section>
    <div className="mt-10 flex flex-wrap justify-end gap-3 border-t pt-5"><Button asChild variant="outline"><Link href={`/applications/${id}/preview`}>View full application</Link></Button><Button asChild><Link href={readiness.ready ? `/applications/${id}/preview` : `/applications/${id}/questions`}>{readiness.ready ? "Review and generate" : "Continue questions"} <ArrowRight /></Link></Button></div>
  </div>;
}

function Metric({ label, value, good, attention }: { label: string; value: number; good?: boolean; attention?: boolean }) { return <div className="flex items-center gap-3 px-4 py-4"><span className={`flex h-8 w-8 items-center justify-center rounded-md ${attention ? "bg-amber-50 text-amber-800" : good ? "bg-emerald-50 text-emerald-800" : "bg-accent text-primary"}`}>{attention ? <CircleAlert className="h-4 w-4" /> : good ? <CheckCircle2 className="h-4 w-4" /> : <span className="text-sm font-semibold">{value}</span>}</span><span className="flex-1 text-sm text-muted-foreground">{label}</span><strong className="text-lg tabular-nums">{value}</strong></div>; }
function FieldRow({ field }: { field: { id: string; finalValue: string | null; proposedValue: string | null; sourceReference: string | null; populationMethod: string; reviewState: string; validationState: string; templateField: { displayLabel: string; required: boolean } } }) { return <div className="grid gap-3 px-3 py-4 md:grid-cols-[1fr_1.2fr_180px]"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium">{field.templateField.displayLabel}</h3>{field.templateField.required && <span className="text-xs text-muted-foreground">Required</span>}</div><p className="mt-1 text-sm text-muted-foreground">{field.sourceReference ?? "Still needs an answer"}</p></div><div className={field.finalValue || field.proposedValue ? "text-sm leading-6" : "text-sm italic text-muted-foreground"}>{field.finalValue ?? field.proposedValue ?? "No value available"}</div><div className="flex flex-wrap gap-2"><StatusBadge status={field.reviewState} />{field.validationState !== "VALID" && <StatusBadge status={field.validationState} />}</div></div>; }
