import { describe, expect, it } from "vitest";
import { calculateDraftReadiness, chooseCanonicalValue, formatCurrency, formatDate, mapTemplateFields, preserveStaffOverride, snapshotTemplateVersion, validateMappingPath, type CanonicalApplicationData, type TemplateFieldConfig } from "@/lib/applications/mapping";
import { safeApplicationFilename } from "@/lib/applications/filename";

const field = (overrides: Partial<TemplateFieldConfig> = {}): TemplateFieldConfig => ({ id: "tf-1", fieldKey: "legal_name", displayLabel: "Legal name", fieldType: "TEXT", required: true, canonicalFieldPath: "client.legalName", validationRules: null, conditionalRules: null, formattingRules: null, ...overrides });
const data = (overrides: Partial<CanonicalApplicationData> = {}): CanonicalApplicationData => ({ values: { "client.legalName": { value: "Jordan Rivera", sourceType: "CANONICAL_PROFILE", sourceReference: "Canonical client profile" }, "finances.earned": { value: 100000, sourceType: "DOCUMENT", sourceReference: "Income statement" }, "finances.benefits": { value: 50000, sourceType: "DOCUMENT", sourceReference: "Benefits letter" }, "finances.monthlyEarnedIncome": { value: 100000, sourceType: "DOCUMENT", sourceReference: "Income statement" }, "finances.monthlyBenefitsIncome": { value: 50000, sourceType: "DOCUMENT", sourceReference: "Benefits letter" }, "finances.otherIncome": { value: 0, sourceType: "CANONICAL_PROFILE", sourceReference: "Canonical client profile" } }, household: [], ...overrides });

describe("application template mapping", () => {
  it("maps canonical information with its source", () => expect(mapTemplateFields([field()], data())[0]).toMatchObject({ finalValue: "Jordan Rivera", populationMethod: "CANONICAL_PROFILE", sourceReference: "Canonical client profile" }));
  it("gives reviewed document values precedence", () => expect(chooseCanonicalValue({ value: "Case value", sourceType: "CANONICAL_PROFILE", sourceReference: "Case" }, [{ value: "Pending", sourceReference: "Draft extraction", reviewed: false }, { value: "Reviewed", sourceReference: "State identification", reviewed: true }])).toMatchObject({ value: "Reviewed", sourceReference: "State identification" }));
  it("preserves explicit staff overrides during recomputation", () => expect(preserveStaffOverride({ populationMethod: "STAFF_ENTRY", finalValue: "Confirmed value" }, mapTemplateFields([field()], data())[0])).toBe(true));
  it("calculates derived household size", () => expect(mapTemplateFields([field({ canonicalFieldPath: "derived.householdSize", fieldType: "NUMBER" })], data({ household: [{ name: "Child", relationship: "Child", dateOfBirth: null, monthlyIncomeCents: null }] }))[0].finalValue).toBe("2"));
  it("calculates derived total monthly income", () => expect(mapTemplateFields([field({ canonicalFieldPath: "derived.totalMonthlyIncome", fieldType: "CURRENCY", formattingRules: "CURRENCY_USD" })], data())[0].finalValue).toBe("$1,500.00"));
  it("formats dates deterministically", () => expect(formatDate("1990-05-08")).toBe("05/08/1990"));
  it("formats currency from stored cents", () => expect(formatCurrency(145000)).toBe("$1,450.00"));
  it("maps a repeating household group", () => { const result = mapTemplateFields([field({ canonicalFieldPath: "derived.householdTable", fieldType: "HOUSEHOLD_TABLE" })], data({ household: [{ name: "Riley Rivera", relationship: "Child", dateOfBirth: "2017-04-12", monthlyIncomeCents: 0 }] }))[0]; expect(JSON.parse(result.finalValue ?? "[]")).toEqual([{ name: "Riley Rivera", relationship: "Child", dateOfBirth: "2017-04-12", monthlyIncomeCents: 0 }]); });
  it("marks conditional fields not applicable", () => { const result = mapTemplateFields([field({ conditionalRules: JSON.stringify({ path: "client.veteranStatus", equals: "Yes" }) })], data())[0]; expect(result.reviewState).toBe("NOT_APPLICABLE"); });
  it("detects required missing fields", () => expect(mapTemplateFields([field({ canonicalFieldPath: "client.mailingAddress" })], data())[0]).toMatchObject({ reviewState: "NEEDS_ANSWER", validationState: "MISSING" }));
  it("propagates conflicts without choosing a value", () => expect(mapTemplateFields([field()], data({ conflicts: { "client.legalName": { values: ["Jordan Rivera", "Jordan R. Rivera"], sourceReference: "Two source documents" } } }))[0]).toMatchObject({ finalValue: null, reviewState: "CONFLICT", validationState: "CONFLICT" }));
  it("blocks readiness until required conflicts and missing values are resolved", () => expect(calculateDraftReadiness([{ required: true, finalValue: null, reviewState: "CONFLICT", validationState: "CONFLICT" }, { required: true, finalValue: "Complete", reviewState: "AUTOMATICALLY_COMPLETED", validationState: "VALID" }])).toEqual({ ready: false, blockingCount: 1, completedCount: 1, totalCount: 2 }));
  it("snapshots the selected template version", () => expect(snapshotTemplateVersion({ version: 4 })).toBe(4));
  it("rejects invalid canonical mapping paths", () => expect(validateMappingPath("invented.secretPath", new Set(["client.legalName"]))).toBe(false));
  it("creates safe generated filenames", () => expect(safeApplicationFilename("family-pathways-application-{client}-v{version}.pdf", { clientName: "Jordan Rivera ../../", version: 2 })).toBe("family-pathways-application-jordan-rivera-v2.pdf"));
});
