import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, Check, ExternalLink, RotateCcw, X } from "lucide-react";
import { addReviewNoteAction, approvePacketAction, overrideRequirementAction, returnPacketAction, reviewPacketFieldAction } from "@/app/actions/packets";
import { db } from "@/lib/db";
import { requireRole } from "@/lib/auth/session";
import { canApprovePacket } from "@/lib/packets/approval";
import { parsePacketSnapshot } from "@/lib/packets/snapshot";
import { StatusBadge } from "@/components/status-badge";
import { SectionHeading } from "@/components/section-heading";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { SubmitButton } from "@/components/submit-button";
import { formatDate } from "@/lib/format";

export default async function PacketReviewPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string }> }) {
  await requireRole(["REVIEWER"]); const { id } = await params; const { error } = await searchParams;
  const packet = await db.applicationPacket.findUnique({ where: { id }, include: { fields: true, reviewNotes: { include: { author: true }, orderBy: { createdAt: "asc" } }, requirementOverrides: { include: { reviewer: true }, orderBy: { createdAt: "asc" } }, approvedBy: true } }); if (!packet) notFound();
  let snapshot; try { snapshot = parsePacketSnapshot(packet.snapshotJson); } catch { notFound(); }
  const overridden = new Set(packet.requirementOverrides.map((item) => item.requirementId));
  const approval = canApprovePacket({ status: packet.status, fields: packet.fields, unresolvedConflicts: packet.unresolvedConflicts, requirements: snapshot.requirements.map((item) => ({ ...item, overridden: overridden.has(item.id) })) });
  const active = packet.status === "READY_FOR_REVIEW" || packet.status === "IN_REVIEW";
  return <div><div className="flex flex-wrap items-end justify-between gap-5 border-b pb-6"><div><Link href="/review" className="text-sm font-medium text-primary underline underline-offset-4">Back to review queue</Link><h1 className="mt-3 text-3xl font-semibold tracking-[-0.03em]">Review {packet.referenceNumber}</h1><p className="mt-2 text-sm text-muted-foreground">Internal review summary · {snapshot.client.preferredName ?? snapshot.client.legalName} · {snapshot.program.name} · Snapshot from {formatDate(snapshot.generatedAt)}</p></div><div className="flex flex-wrap items-center gap-3"><StatusBadge status={packet.status} /><Button asChild variant="outline"><Link href={`/packets/${id}`}>Review summary preview <ExternalLink /></Link></Button></div></div>
    {error && <div role="alert" className="mt-6 border border-red-300 bg-red-50 p-4 text-sm text-red-900">Approval blocked: {error}</div>}
    {packet.unresolvedConflicts > 0 && <div className="mt-6 flex gap-3 border border-red-300 bg-red-50 p-4 text-sm text-red-900"><AlertTriangle className="h-5 w-5 shrink-0" />This packet snapshot contains {packet.unresolvedConflicts} unresolved conflict{packet.unresolvedConflicts === 1 ? "" : "s"}. Return it for correction; conflicts cannot be overridden.</div>}
    <section className="mt-10"><SectionHeading index="01" title="Application fields" description="Compare every value with the named snapshot source. The first review decision moves the packet into review." /><div className="mt-5 border bg-white">{packet.fields.map((field) => <ReviewField key={field.id} packetId={id} field={field} active={active} />)}</div></section>
    <section className="mt-12"><SectionHeading index="02" title="Requirement evidence" description="These states were calculated when this packet version was generated and do not change when the live case changes." /><div className="mt-5 border bg-white">{snapshot.requirements.map((item) => { const existing = packet.requirementOverrides.find((override) => override.requirementId === item.id); return <div key={item.id} className="grid gap-4 border-b p-5 last:border-b-0 lg:grid-cols-[180px_1fr_320px]"><div><StatusBadge status={item.state} /></div><div><div className="font-medium">{item.name}</div><p className="mt-1 text-sm text-muted-foreground">{item.reason}</p>{existing && <div className="mt-3 border border-blue-300 bg-blue-50 p-3 text-sm text-blue-950"><strong>Written override:</strong> {existing.note}<div className="mt-1 text-xs">{existing.reviewer.name} · {formatDate(existing.createdAt)}</div></div>}</div><div>{active && item.isRequired && item.state !== "SATISFIED" && !existing ? <form action={overrideRequirementAction.bind(null, id)} className="space-y-2"><input type="hidden" name="requirementId" value={item.id} /><label htmlFor={`override-${item.id}`} className="text-xs font-semibold">Written override reason</label><Textarea id={`override-${item.id}`} name="note" required minLength={10} placeholder="Explain why staff may proceed without this requirement." /><SubmitButton variant="outline" size="sm" pendingLabel="Recording…">Record override</SubmitButton></form> : !item.isRequired || item.state === "SATISFIED" ? <p className="text-xs text-muted-foreground">No override needed.</p> : null}</div></div>; })}</div></section>
    <section className="mt-12"><SectionHeading index="03" title="Review notes" description="General notes provide context but do not override a requirement. Use the requirement-specific form above for an override." /><div className="mt-5 grid gap-6 lg:grid-cols-[1fr_0.7fr]"><div className="border bg-white">{packet.reviewNotes.length ? packet.reviewNotes.map((note) => <div key={note.id} className="border-b p-4 last:border-b-0"><p>{note.note}</p><p className="mt-2 text-xs text-muted-foreground">{note.author.name} · {formatDate(note.createdAt)}</p></div>) : <div className="p-6 text-sm text-muted-foreground">No general review notes have been added.</div>}</div>{active && <form action={addReviewNoteAction.bind(null, id)} className="border bg-white p-5"><label htmlFor="note" className="text-sm font-semibold">Add reviewer note</label><Textarea id="note" name="note" required minLength={3} maxLength={2000} className="mt-2" /><SubmitButton className="mt-3" variant="outline" pendingLabel="Adding…">Add note</SubmitButton></form>}</div></section>
    <section className="mt-12 border-t-2 border-foreground pt-6"><div className="flex flex-wrap items-start justify-between gap-6"><div><h2 className="text-2xl font-semibold">Complete review</h2><ul aria-live="polite" className="mt-3 space-y-1 text-sm text-muted-foreground">{approval.allowed ? <li className="text-emerald-700">All approval rules are satisfied.</li> : approval.reasons.map((reason) => <li key={reason}>• {reason}</li>)}</ul><Link href={`/review/${id}/versions`} className="mt-4 inline-block text-sm font-semibold text-primary underline underline-offset-4">View packet version history</Link></div>{active && <div className="flex flex-wrap gap-3"><form action={returnPacketAction.bind(null, id)} className="flex gap-2"><Input name="note" aria-label="Return note" placeholder="Required correction" required minLength={3} /><SubmitButton variant="outline" pendingLabel="Returning…"><RotateCcw /> Return</SubmitButton></form><form action={approvePacketAction.bind(null, id)}><SubmitButton pendingLabel="Checking…"><Check /> Approve packet</SubmitButton></form></div>}</div></section></div>;
}

function ReviewField({ packetId, field, active }: { packetId: string; field: { id: string; fieldLabel: string; value: string; sourceType: string; sourceReference: string | null; isRequired: boolean; reviewStatus: string; reviewerNote: string | null }; active: boolean }) {
  return <div className="grid gap-4 border-b p-5 last:border-b-0 lg:grid-cols-[1fr_1.1fr_240px]"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium">{field.fieldLabel}</h3>{field.isRequired && <span className="text-xs text-muted-foreground">Required</span>}</div><p className="mt-2 text-base">{field.value || "Not provided"}</p></div><div className="rounded-md bg-secondary p-3 text-sm"><div className="text-xs font-medium text-muted-foreground">Snapshot source</div><p className="mt-1.5">{field.sourceType.replaceAll("_", " ")} · {field.sourceReference ?? "No reference"}</p>{field.reviewerNote && <p className="mt-2 text-muted-foreground">{field.reviewerNote}</p>}</div><div>{active ? <form action={reviewPacketFieldAction.bind(null, packetId, field.id)} className="space-y-2"><Input name="note" placeholder="Optional field note" maxLength={500} /><div className="grid grid-cols-2 gap-2"><SubmitButton name="status" value="APPROVED" variant="outline" pendingLabel="Saving…"><Check /> Approve</SubmitButton><SubmitButton name="status" value="REJECTED" variant="outline" pendingLabel="Saving…"><X /> Reject</SubmitButton></div></form> : null}<div className="mt-2"><StatusBadge status={field.reviewStatus} /></div></div></div>;
}
