import Link from "next/link";
import { notFound } from "next/navigation";
import { Download, FileJson, Send } from "lucide-react";
import { createSecurePacketDownloadAction, submitPacketAction } from "@/app/actions/packets";
import { db } from "@/lib/db";
import { activateOrganizationContext, canAccessPacket, requireUser } from "@/lib/auth/session";
import { parsePacketSnapshot } from "@/lib/packets/snapshot";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { SubmitButton } from "@/components/submit-button";
import { PrintButton } from "@/components/print-button";
import { formatDate } from "@/lib/format";

export default async function PacketPreviewPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ submitted?: string; notice?: string }> }) {
  const user = activateOrganizationContext(await requireUser()); const { id } = await params; const messages = await searchParams; if (!(await canAccessPacket(user, id))) notFound();
  const packet = await db.applicationPacket.findUnique({ where: { id }, include: { fields: true, reviewNotes: { include: { author: true }, orderBy: { createdAt: "asc" } }, requirementOverrides: { include: { reviewer: true }, orderBy: { createdAt: "asc" } }, approvedBy: true } }); if (!packet) notFound();
  let snapshot; try { snapshot = parsePacketSnapshot(packet.snapshotJson); } catch { notFound(); }
  const submitAction = submitPacketAction.bind(null, id);
  return <div>
    <div className="no-print flex flex-wrap items-center justify-between gap-4 border-b pb-5"><div><Link href={`/cases/${packet.clientCaseId}/packet`} className="text-sm font-semibold text-primary underline underline-offset-4">Back to case</Link><h1 className="mt-2 text-3xl font-semibold tracking-tight">Review summary preview</h1><p className="mt-1 text-sm text-muted-foreground">Internal case snapshot - not the completed housing application.</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline"><a href={`/api/packets/${id}/json`}><FileJson /> JSON</a></Button><Button asChild variant="outline"><a href={`/api/packets/${id}/pdf`}><Download /> PDF</a></Button>{packet.status === "APPROVED" && <form action={createSecurePacketDownloadAction.bind(null, id)}><SubmitButton variant="outline" pendingLabel="Creating…"><Download /> One-use 15-minute link</SubmitButton></form>}<PrintButton />{packet.status === "DRAFT" && user.role === "CASEWORKER" && <form action={submitAction}><SubmitButton pendingLabel="Submitting…"><Send /> Submit for review</SubmitButton></form>}{["REVIEWER", "SUPERVISOR", "AUDITOR"].includes(user.role) && packet.status !== "DRAFT" && <Button asChild><Link href={`/review/${id}`}>Open review</Link></Button>}</div></div>
    {messages.submitted && <div role="status" className="no-print mt-5 border border-emerald-300 bg-emerald-50 p-4 text-sm text-emerald-900">Packet version {packet.version} was submitted for human review.</div>}
    {messages.notice && <div role="status" className="no-print mt-5 border border-blue-300 bg-blue-50 p-4 text-sm text-blue-900">{messages.notice}</div>}
    <div className="no-print mt-5 border border-zinc-300 bg-white p-4 text-sm"><strong>Snapshot notice:</strong> This preview shows the source data captured on {formatDate(snapshot.generatedAt)}. Later case edits do not change this packet version.</div>
    <article className="print-card mx-auto mt-8 max-w-5xl border bg-white p-6 sm:p-10"><header className="grid gap-6 border-b-2 border-foreground pb-8 sm:grid-cols-[1fr_auto]"><div><p className="text-sm font-semibold text-primary">Internal application review summary</p><h2 className="mt-2 text-4xl font-semibold tracking-[-0.04em]">{packet.referenceNumber}</h2><p className="mt-2 text-sm text-muted-foreground">Version {packet.version} · Generated {formatDate(packet.generatedAt)}{packet.submittedAt ? ` · Submitted ${formatDate(packet.submittedAt)}` : " · Draft"}</p></div><StatusBadge status={packet.status} /></header>
      <div className="mt-6 border border-blue-300 bg-blue-50 p-4 text-sm text-blue-950"><strong>Human review required.</strong> This packet supports trained staff. It does not determine eligibility, rank clients, or make legal conclusions.</div>
      <PacketSection number="01" title="Client and household"><dl className="grid border sm:grid-cols-3"><Item label="Legal name" value={snapshot.client.legalName} /><Item label="Preferred name" value={snapshot.client.preferredName ?? "Not provided"} /><Item label="Date of birth" value={snapshot.client.dateOfBirth ?? "Not provided"} /></dl><div className="mt-3 border">{snapshot.household.length ? snapshot.household.map((member, index) => <div key={`${member.name}-${index}`} className="grid border-b p-3 last:border-b-0 sm:grid-cols-2"><span>{member.name}</span><span className="text-muted-foreground">{member.relationship}</span></div>) : <div className="p-3 text-sm text-muted-foreground">No additional household members recorded.</div>}</div></PacketSection>
      <PacketSection number="02" title="Selected program"><h4 className="font-semibold">{snapshot.program.name}</h4><p className="mt-1 text-sm text-muted-foreground">{snapshot.program.organization} · Fictional demonstration organization</p><p className="mt-3 text-sm leading-6">{snapshot.program.description}</p></PacketSection>
      <PacketSection number="03" title="Application fields"><div className="border">{packet.fields.map((field) => <div key={field.id} className="grid gap-2 border-b p-4 last:border-b-0 sm:grid-cols-[1fr_1.4fr_1fr]"><div className="font-medium">{field.fieldLabel}</div><div>{field.value || "Not provided"}</div><div className="text-sm text-muted-foreground">Source: {field.sourceReference ?? field.sourceType}</div></div>)}</div></PacketSection>
      <PacketSection number="04" title="Required-document checklist"><div className="border">{snapshot.requirements.map((requirement) => <div key={requirement.id} className="grid gap-3 border-b p-4 last:border-b-0 sm:grid-cols-[180px_1fr]"><StatusBadge status={requirement.state} /><div><div className="font-medium">{requirement.name}</div><div className="mt-1 text-sm text-muted-foreground">{requirement.reason}</div></div></div>)}</div></PacketSection>
      <PacketSection number="05" title="Supporting documents and missing information"><div className="grid gap-4 md:grid-cols-2"><div className="border p-4"><h4 className="font-semibold">Supporting documents</h4><ul className="mt-3 space-y-2 text-sm">{snapshot.documents.length ? snapshot.documents.map((document, index) => <li key={`${document.originalFilename}-${index}`}>{document.originalFilename} · {document.category.replaceAll("_", " ")} · {document.processingStatus.toLowerCase()}</li>) : <li>No documents listed.</li>}</ul></div><div className="border p-4"><h4 className="font-semibold">Missing information</h4><ul className="mt-3 space-y-2 text-sm">{snapshot.missingInformation.length ? snapshot.missingInformation.map((item) => <li key={item}>{item}</li>) : <li>No mandatory information was missing when this version was generated.</li>}</ul></div></div>{snapshot.reviewItems.length > 0 && <div className="mt-4 border border-amber-300 bg-amber-50 p-4"><h4 className="font-semibold text-amber-950">Items for staff review</h4><ul className="mt-2 space-y-2 text-sm text-amber-950">{snapshot.reviewItems.map((item) => <li key={item.code}>{item.message}</li>)}</ul></div>}</PacketSection>
      <PacketSection number="06" title="Review notes and overrides"><div className="border">{packet.reviewNotes.map((note) => <div key={note.id} className="border-b p-4"><p>{note.note}</p><p className="mt-2 text-xs text-muted-foreground">{note.author.name} · {formatDate(note.createdAt)}</p></div>)}{packet.requirementOverrides.map((override) => <div key={override.id} className="border-b border-blue-200 bg-blue-50 p-4 last:border-b-0"><p className="font-semibold">Override: {override.requirementName}</p><p className="mt-1">{override.note}</p><p className="mt-2 text-xs text-muted-foreground">{override.reviewer.name} · {formatDate(override.createdAt)}</p></div>)}{!packet.reviewNotes.length && !packet.requirementOverrides.length && <div className="p-4 text-sm text-muted-foreground">No review notes or requirement overrides.</div>}</div></PacketSection>
      <footer className="mt-10 border-t-2 border-foreground pt-5 text-xs text-muted-foreground">Generated for demonstration use with synthetic data. A qualified person must confirm all fields and sources before submission.</footer></article></div>;
}

function PacketSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section data-section={number} className="mt-10"><div className="mb-5 border-b pb-3"><h3 className="text-xl font-semibold">{title}</h3></div>{children}</section>; }
function Item({ label, value }: { label: string; value: string }) { return <div className="border-b p-4 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><dt className="text-xs font-semibold text-muted-foreground">{label}</dt><dd className="mt-1">{value}</dd></div>; }
