import { notFound } from "next/navigation";
import { Check, FileText, Pencil, Trash2, X } from "lucide-react";
import { batchApproveHighConfidenceAction, deleteDocumentAction, escalateExtractionAction, retryDocumentProcessingAction, uploadDocumentAction, reviewExtractionAction } from "@/app/actions/documents";
import { db } from "@/lib/db";
import { activateOrganizationContext, canAccessCase, requireRole } from "@/lib/auth/session";
import { CaseHeader } from "@/features/cases/case-header";
import { SectionHeading } from "@/components/section-heading";
import { StatusBadge } from "@/components/status-badge";
import { Input } from "@/components/ui/input";
import { formatDate } from "@/lib/format";
import { SubmitButton } from "@/components/submit-button";
import { UploadDocumentForm } from "@/features/documents/upload-document-form";
import { DocumentReviewWorkbench } from "@/components/document-review-workbench";
import { getLegacyOrStoredObject } from "@/lib/storage";
import { preprocessImage } from "@/lib/document-processing/preprocess";
import { renderPdfToPngDataUrls } from "@/lib/document-processing/pdf-to-images";

export default async function DocumentsPage({ params }: { params: Promise<{ id: string }> }) {
  const user = activateOrganizationContext(await requireRole(["CASEWORKER", "REVIEWER", "SUPERVISOR", "AUDITOR"]));
  const { id } = await params;
  if (!(await canAccessCase(user, id))) notFound();
  const [clientCase, documentProfiles] = await Promise.all([db.clientCase.findUnique({ where: { id }, include: { documents: { include: { extractedFields: { include: { revisions: { include: { reviewer: { select: { name: true } } }, orderBy: { createdAt: "desc" } } } }, uploadedBy: true }, orderBy: { uploadedAt: "desc" } } } }), db.documentProfile.findMany({ where: { organizationId: user.organizationId, active: true }, orderBy: { key: "asc" } })]);
  if (!clientCase) notFound();
  const originals = new Map(clientCase.documents.map((document) => [document.id, document.originalFilename]));
  const fieldSources = new Map<string, Array<{ filename: string; value: string; status: string }>>();
  for (const document of clientCase.documents) for (const field of document.extractedFields) {
    const values = fieldSources.get(field.fieldName) ?? [];
    values.push({ filename: document.originalFilename, value: field.reviewedValue ?? field.normalizedValue ?? field.extractedValue, status: field.reviewStatus });
    fieldSources.set(field.fieldName, values);
  }
  const evidence = await Promise.all(clientCase.documents.map(async (document) => {
    if (document.processingStatus === "DELETED" || document.quarantineStatus !== "CLEAR" || !document.storageKey && !document.storagePath) return { id: document.id, pages: [] as Array<{ page: number; dataUrl: string }> };
    try {
      const bytes = await getLegacyOrStoredObject(document);
      if (document.fileType === "application/pdf") return { id: document.id, pages: (await renderPdfToPngDataUrls(bytes, document.originalFilename)).map((dataUrl, index) => ({ page: index + 1, dataUrl })) };
      if (document.fileType.startsWith("image/")) return { id: document.id, pages: [{ page: 1, dataUrl: (await preprocessImage(bytes)).dataUrl }] };
    } catch { /* the review surface remains usable with retained text evidence */ }
    return { id: document.id, pages: [] as Array<{ page: number; dataUrl: string }> };
  }));
  const pageByDocument = new Map(evidence.map((item) => [item.id, item.pages]));
  return <div>
    <CaseHeader clientCase={clientCase} />
    <section className="mt-10">
      <SectionHeading index="03" title="Supporting documents" description="Extraction is a proposal. Staff must approve, correct, or classify every value before it can be relied on." />
      {user.role === "CASEWORKER" && <UploadDocumentForm action={uploadDocumentAction.bind(null, id)} categories={documentProfiles.length ? documentProfiles.map((profile) => profile.category) : undefined} />}
      <div className="mt-7 space-y-5">{clientCase.documents.length ? clientCase.documents.map((document) => {
        const fields = document.extractedFields.map((field) => ({ ...field, conflicts: (fieldSources.get(field.fieldName) ?? []).filter((source) => source.filename !== document.originalFilename && source.value.trim().toLowerCase() !== (field.reviewedValue ?? field.normalizedValue ?? field.extractedValue).trim().toLowerCase()) }));
        const pendingHighConfidence = document.extractedFields.filter((field) => field.reviewStatus === "PENDING" && field.confidence >= 0.9 && field.sourcePage !== null && Boolean(field.sourceText?.trim())).length;
        return <article id={`document-${document.id}`} key={document.id} className="overflow-hidden border bg-white shadow-[0_12px_35px_rgba(15,23,42,0.05)]">
          <header className="grid gap-4 border-b bg-secondary p-5 sm:grid-cols-[auto_1fr_auto]">
            <div className="flex h-10 w-10 items-center justify-center border bg-white"><FileText className="h-5 w-5 text-primary" /></div>
            <div><h3 className="font-semibold">{document.originalFilename}</h3><p className="mt-1 text-xs text-muted-foreground">{document.documentCategory.replaceAll("_", " ")} · Uploaded {formatDate(document.uploadedAt)} by {document.uploadedBy.name}{document.expirationDate ? ` · Expires ${formatDate(document.expirationDate)}` : ""}{document.duplicateOfId ? ` · Duplicate of ${originals.get(document.duplicateOfId) ?? "an existing document"}` : ""}</p></div>
            <div className="flex flex-wrap gap-2"><StatusBadge status={document.processingStatus} />{document.quarantineStatus !== "CLEAR" && <StatusBadge status={document.quarantineStatus} />}</div>
          </header>
          {document.duplicateOfId && <div role="status" className="border-b border-amber-200 bg-amber-50 px-5 py-3 text-xs text-amber-950">This upload is a duplicate and was not stored again. Compare it with <a className="font-semibold underline" href={`#document-${document.duplicateOfId}`}>{originals.get(document.duplicateOfId) ?? "the original document"}</a>.</div>}
          {document.processingStatus === "COMPLETED_WITH_REVIEW" && <div role="alert" className="border-b border-amber-300 bg-amber-50 px-5 py-3 text-sm text-amber-950">{document.processingError ?? "Extraction abstained on one or more uncertain values. Review the highlighted reasons before relying on this document."}</div>}
          {["FAILED", "QUARANTINED", "DUPLICATE"].includes(document.processingStatus) && <div role="alert" className="flex flex-wrap items-center justify-between gap-4 border-b border-red-300 bg-red-50 p-4 text-sm text-red-900"><span>{document.processingError ?? "This document is unavailable."}</span>{user.role === "CASEWORKER" && document.processingStatus === "FAILED" && <form action={retryDocumentProcessingAction.bind(null, id, document.id)}><SubmitButton variant="outline" size="sm" pendingLabel="Retrying…">Retry processing</SubmitButton></form>}</div>}
          {document.extractedFields.length ? <DocumentReviewWorkbench documentId={document.id} fields={fields.map((field) => ({ id: field.id, fieldName: field.fieldName, sourcePage: field.sourcePage, sourceText: field.sourceText, confidence: field.confidence, reviewStatus: field.reviewStatus, reviewReason: field.reviewReason, sourceRegionJson: field.sourceRegionJson, conflicts: field.conflicts }))} pages={pageByDocument.get(document.id) ?? []} batchForm={user.role !== "AUDITOR" && pendingHighConfidence > 0 ? <form action={batchApproveHighConfidenceAction.bind(null, id, document.id)} className="flex items-center gap-2"><input type="hidden" name="threshold" value="0.9" /><SubmitButton size="sm" variant="outline" pendingLabel="Approving…">Approve {pendingHighConfidence} high-confidence</SubmitButton></form> : null}>{document.extractedFields.map((field) => <Extraction key={field.id} field={{ ...field, conflicts: fields.find((item) => item.id === field.id)?.conflicts ?? [] }} clientCaseId={id} editable={user.role !== "AUDITOR"} />)}</DocumentReviewWorkbench> : <div className="p-5 text-sm text-muted-foreground">No extracted fields are available for this document.</div>}
          {user.role === "CASEWORKER" && !document.deletedAt && <form action={deleteDocumentAction.bind(null, id, document.id)} className="flex flex-wrap items-end gap-3 border-t bg-red-50/50 p-4"><div className="min-w-72 flex-1"><label htmlFor={`delete-${document.id}`} className="text-xs font-semibold">Deletion reason</label><Input id={`delete-${document.id}`} name="reason" required minLength={10} placeholder="Why this document may be removed" className="mt-1" /></div><SubmitButton variant="outline" size="sm" pendingLabel="Deleting…"><Trash2 /> Delete document</SubmitButton></form>}
        </article>;
      }) : <div className="border bg-white p-12 text-center"><FileText className="mx-auto h-8 w-8 text-muted-foreground" /><h3 className="mt-4 text-lg font-semibold">No documents uploaded</h3><p className="mt-2 text-sm text-muted-foreground">Upload a PDF, PNG, or JPEG to begin human-reviewed extraction.</p></div>}</div>
    </section>
  </div>;
}

function Extraction({ field, clientCaseId, editable }: { field: { id: string; fieldName: string; extractedValue: string; normalizedValue: string | null; reviewedValue: string | null; confidence: number; sourcePage: number | null; sourceText: string | null; reviewStatus: string; reviewReason: string | null; validationState: string; sourceRegionJson: string | null; revisions: Array<{ id: string; beforeValue: string | null; afterValue: string | null; beforeStatus: string; afterStatus: string; beforeReason: string | null; afterReason: string | null; sourceRevision: number; createdAt: Date; reviewer: { name: string } | null }>; conflicts: Array<{ filename: string; value: string; status: string }> }; clientCaseId: string; editable: boolean }) {
  const action = reviewExtractionAction.bind(null, clientCaseId, field.id);
  const currentValue = field.reviewedValue ?? field.normalizedValue ?? field.extractedValue;
  const why = field.reviewReason ?? (field.reviewStatus === "PENDING" && field.confidence < 0.75 ? "Confidence is below the 75% acceptance threshold." : field.reviewStatus === "CONFLICTING" ? "Another document contains a different value for this field." : !field.sourceText ? "No evidence snippet was retained; verify directly against the document." : field.reviewStatus === "PENDING" ? "This proposal has not been accepted by a reviewer." : null);
  return <div data-testid={`extraction-${field.fieldName}`} data-review-field data-field-id={field.id} data-selected="false" className="grid gap-4 border-b p-5 transition-colors last:border-b-0 data-[selected=true]:bg-blue-50/60 lg:grid-cols-[1fr_1.1fr_240px]">
    <div><div className="flex flex-wrap items-center gap-2"><span className="font-medium capitalize">{field.fieldName.replaceAll("_", " ")}</span><StatusBadge status={field.reviewStatus} /><StatusBadge status={field.validationState} /></div><div className="mt-2 text-base">{currentValue || "—"}</div><div className="mt-1 text-xs text-muted-foreground">Original: {field.extractedValue} · Confidence {Math.round(field.confidence * 100)}% · Page {field.sourcePage ?? "unknown"}</div>{why && <p className="mt-2 rounded border border-amber-200 bg-amber-50 px-2.5 py-2 text-xs text-amber-950"><strong>Why review is needed:</strong> {why}</p>}{field.conflicts.length > 0 && <div className="mt-2 rounded border border-red-200 bg-red-50 px-2.5 py-2 text-xs text-red-900"><strong>Conflict comparison</strong>{field.conflicts.map((conflict) => <div key={`${conflict.filename}-${conflict.value}`} className="mt-1 flex justify-between gap-3"><span>{conflict.filename}</span><span className="font-medium">{conflict.value} · {conflict.status}</span></div>)}</div>}</div>
    <div className="rounded-md bg-secondary p-3"><div className="text-xs font-medium text-muted-foreground">Source text</div><blockquote className="mt-1.5 text-sm leading-6">{field.sourceText ?? "No source text retained."}</blockquote><div className="mt-3 text-[11px] text-muted-foreground">Click any field to keep its page and evidence anchored in the rail.</div></div>
    {editable ? <div className="space-y-2"><form action={action} className="space-y-2"><Input data-review-input name="reviewedValue" aria-label={`Reviewed value for ${field.fieldName}`} defaultValue={field.reviewedValue ?? field.normalizedValue ?? field.extractedValue} /><textarea name="reason" aria-label={`Review reason for ${field.fieldName}`} defaultValue={field.reviewReason ?? ""} placeholder="Reviewer comment" className="min-h-16 w-full border bg-white px-2.5 py-2 text-xs" /><div className="grid grid-cols-3 gap-1"><SubmitButton data-review-action="approve" name="status" value="APPROVED" size="sm" variant="outline" title="Approve (A)" pendingLabel="…"><Check /></SubmitButton><SubmitButton name="status" value="EDITED" size="sm" variant="outline" title="Save edit (E)" pendingLabel="…"><Pencil /></SubmitButton><SubmitButton data-review-action="reject" name="status" value="REJECTED" size="sm" variant="outline" title="Reject (R)" pendingLabel="…"><X /></SubmitButton></div><div className="flex gap-2"><select name="status" aria-label={`Exceptional review state for ${field.fieldName}`} defaultValue="UNREADABLE" className="h-9 min-w-0 flex-1 border bg-white px-2 text-xs">{["UNREADABLE", "MISSING", "EXPIRED", "INVALID", "CONFLICTING"].map((status) => <option key={status}>{status}</option>)}</select><SubmitButton size="sm" variant="outline" pendingLabel="Saving…">Save state</SubmitButton></div></form><form action={escalateExtractionAction.bind(null, clientCaseId, field.id)} className="flex gap-2"><Input name="reason" required minLength={10} maxLength={1000} aria-label={`Escalation reason for ${field.fieldName}`} placeholder="Escalation reason (10+ characters)" /><SubmitButton size="sm" variant="outline" pendingLabel="Escalating…">Escalate</SubmitButton></form></div> : <p className="text-sm text-muted-foreground">Read-only audit view</p>}
    {field.revisions.length > 0 && <details className="lg:col-span-3"><summary className="cursor-pointer text-xs font-semibold text-slate-600">Change history · {field.revisions.length} revision{field.revisions.length === 1 ? "" : "s"}</summary><div className="mt-3 overflow-x-auto border"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-2">When</th><th className="px-3 py-2">Reviewer</th><th className="px-3 py-2">Before</th><th className="px-3 py-2">After</th><th className="px-3 py-2">State</th><th className="px-3 py-2">Comment</th></tr></thead><tbody>{field.revisions.map((revision) => <tr key={revision.id} className="border-t"><td className="whitespace-nowrap px-3 py-2">{formatDate(revision.createdAt)}</td><td className="px-3 py-2">{revision.reviewer?.name ?? "Former reviewer"}</td><td className="px-3 py-2">{revision.beforeValue ?? "—"}</td><td className="px-3 py-2">{revision.afterValue ?? "—"}</td><td className="px-3 py-2">{revision.beforeStatus} → {revision.afterStatus}</td><td className="px-3 py-2">{revision.afterReason ?? revision.beforeReason ?? "—"}</td></tr>)}</tbody></table></div></details>}
  </div>;
}
