import { notFound } from "next/navigation";
import { Check, FileText, Pencil, X } from "lucide-react";
import { retryDocumentProcessingAction, uploadDocumentAction, reviewExtractionAction } from "@/app/actions/documents";
import { db } from "@/lib/db";
import { canAccessCase, requireRole } from "@/lib/auth/session";
import { CaseHeader } from "@/features/cases/case-header";
import { SectionHeading } from "@/components/section-heading";
import { StatusBadge } from "@/components/status-badge";
import { Input } from "@/components/ui/input";
import { formatDate } from "@/lib/format";
import { SubmitButton } from "@/components/submit-button";
import { UploadDocumentForm } from "@/features/documents/upload-document-form";

export default async function DocumentsPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireRole(["CASEWORKER", "REVIEWER"]); const { id } = await params; if (!(await canAccessCase(user, id))) notFound(); const clientCase = await db.clientCase.findUnique({ where: { id }, include: { documents: { include: { extractedFields: true, uploadedBy: true }, orderBy: { uploadedAt: "desc" } } } }); if (!clientCase) notFound(); const uploadAction = uploadDocumentAction.bind(null, id);
  return <div><CaseHeader clientCase={clientCase} /><section className="mt-10"><SectionHeading index="03" title="Supporting documents" description="Extraction is a draft. Approve, edit, or reject every value before relying on it." />{user.role === "CASEWORKER" && <UploadDocumentForm action={uploadAction} />}<div className="mt-7 space-y-5">{clientCase.documents.length ? clientCase.documents.map((document) => <article key={document.id} className="border bg-white"><header className="grid gap-4 border-b bg-secondary p-5 sm:grid-cols-[auto_1fr_auto]"><div className="flex h-10 w-10 items-center justify-center border bg-white"><FileText className="h-5 w-5 text-primary" /></div><div><h3 className="font-semibold">{document.originalFilename}</h3><p className="mt-1 text-xs text-muted-foreground">{document.documentCategory.replaceAll("_", " ")} · Uploaded {formatDate(document.uploadedAt)} by {document.uploadedBy.name}{document.expirationDate ? ` · Expires ${formatDate(document.expirationDate)}` : ""}</p></div><StatusBadge status={document.processingStatus} /></header>{document.processingStatus === "FAILED" && <div role="alert" className="flex flex-wrap items-center justify-between gap-4 border-b border-red-300 bg-red-50 p-4 text-sm text-red-900"><span>{document.processingError ?? "Processing did not complete."}</span>{user.role === "CASEWORKER" && <form action={retryDocumentProcessingAction.bind(null, id, document.id)}><SubmitButton variant="outline" size="sm" pendingLabel="Retrying…">Retry processing</SubmitButton></form>}</div>}<div>{document.extractedFields.length ? document.extractedFields.map((field) => <Extraction key={field.id} field={field} clientCaseId={id} />) : <div className="p-5 text-sm text-muted-foreground">No extracted fields are available for this document.</div>}</div></article>) : <div className="border bg-white p-12 text-center"><FileText className="mx-auto h-8 w-8 text-muted-foreground" /><h3 className="mt-4 text-lg font-semibold">No documents uploaded</h3><p className="mt-2 text-sm text-muted-foreground">Try sample-id.pdf or sample-income.pdf for predictable demonstration extraction.</p></div>}</div></section></div>;
}

function Extraction({ field, clientCaseId }: { field: { id: string; fieldName: string; extractedValue: string; reviewedValue: string | null; confidence: number; sourcePage: number | null; sourceText: string | null; reviewStatus: string }; clientCaseId: string }) {
  const action = reviewExtractionAction.bind(null, clientCaseId, field.id);
  return <div data-testid={`extraction-${field.fieldName}`} className="grid gap-4 border-b p-5 last:border-b-0 lg:grid-cols-[1fr_1.2fr_190px]"><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium capitalize">{field.fieldName.replaceAll("_", " ")}</span><StatusBadge status={field.reviewStatus} /></div><div className="mt-2 text-base">{field.reviewedValue ?? field.extractedValue}</div><div className="mt-1 text-xs text-muted-foreground">Confidence {Math.round(field.confidence * 100)}% · Page {field.sourcePage ?? "unknown"}</div></div><div className="rounded-md bg-secondary p-3"><div className="text-xs font-medium text-muted-foreground">Source text</div><blockquote className="mt-1.5 text-sm leading-6">{field.sourceText ?? "No source text retained."}</blockquote></div><form action={action} className="space-y-2"><Input name="reviewedValue" aria-label={`Reviewed value for ${field.fieldName}`} defaultValue={field.reviewedValue ?? field.extractedValue} /><div className="grid grid-cols-3 gap-1"><SubmitButton name="status" value="APPROVED" size="sm" variant="outline" title="Approve" pendingLabel="…"><Check /></SubmitButton><SubmitButton name="status" value="EDITED" size="sm" variant="outline" title="Save edit" pendingLabel="…"><Pencil /></SubmitButton><SubmitButton name="status" value="REJECTED" size="sm" variant="outline" title="Reject" pendingLabel="…"><X /></SubmitButton></div></form></div>;
}
