import { notFound } from "next/navigation";
import Link from "next/link";
import { addRequirementAction, addSubmissionDestinationAction, deleteRequirementAction, updateProgramAction, updateRequirementAction } from "@/app/actions/admin";
import { db } from "@/lib/db";
import { activateOrganizationContext, requireRole } from "@/lib/auth/session";
import { StatusBadge } from "@/components/status-badge";
import { SectionHeading } from "@/components/section-heading";
import { SubmitButton, ConfirmSubmitButton } from "@/components/submit-button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const categories = ["IDENTITY", "INCOME", "RESIDENCY", "HOUSEHOLD", "DISABILITY", "HOMELESSNESS_VERIFICATION", "OTHER"];
export default async function ProgramEditorPage({ params }: { params: Promise<{ id: string }> }) {
  activateOrganizationContext(await requireRole(["ADMIN"])); const { id } = await params; const program = await db.housingProgram.findUnique({ where: { id }, include: { requirements: { orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }, applicationTemplates: { orderBy: [{ name: "asc" }, { version: "desc" }] }, submissionDestinations: { orderBy: { name: "asc" } } } }); if (!program) notFound();
  return <div><p className="text-sm font-semibold text-primary">Program editor</p><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-4xl font-semibold tracking-[-0.04em]">{program.name}</h1><p className="mt-2 text-muted-foreground">{program.organization} · Fictional demonstration organization</p></div><StatusBadge status={program.isActive ? "ACTIVE" : "ARCHIVED"} /></div>
    <section className="mt-10"><SectionHeading index="01" title="Program details" description="Changes affect future requirement checks. Existing packet snapshots remain unchanged." /><form action={updateProgramAction.bind(null, id)} className="mt-5 grid gap-5 border bg-white p-6 sm:grid-cols-2"><Field label="Program name" name="name" value={program.name} required /><Field label="Organization" name="organization" value={program.organization} required /><Area label="Description" name="description" value={program.description} required /><Area label="Income limit notes" name="incomeLimitNotes" value={program.incomeLimitNotes} /><Area label="Household restrictions" name="householdRestrictions" value={program.householdRestrictions} /><Area label="Accessibility notes" name="accessibilityNotes" value={program.accessibilityNotes} /><Area label="Contact information" name="contactInformation" value={program.contactInformation} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isActive" defaultChecked={program.isActive} /> Active and available for selection</label><div className="flex justify-end sm:col-span-2"><SubmitButton pendingLabel="Saving program…">Save program details</SubmitButton></div></form></section>
    <section className="mt-12"><SectionHeading index="02" title="Requirement templates" description="Rules are transparent and deterministic. AI output never sets a final requirement state." /><div className="mt-5 space-y-3">{program.requirements.map((requirement) => <article key={requirement.id} className="border bg-white"><div className="grid gap-3 p-5 md:grid-cols-[1fr_200px_150px]"><div><div className="font-semibold">{requirement.name}</div><div className="mt-1 text-sm text-muted-foreground">{requirement.description}</div></div><div className="text-sm">{requirement.category.replaceAll("_", " ")}</div><div className="text-sm">{requirement.isRequired ? "Required" : "Conditional"}{requirement.expirationPeriodDays ? ` · ${requirement.expirationPeriodDays} days` : ""}</div></div><details className="border-t bg-secondary"><summary className="cursor-pointer px-5 py-3 text-sm font-semibold">Edit requirement</summary><div className="grid gap-4 border-t p-5 lg:grid-cols-[1fr_auto]"><RequirementForm action={updateRequirementAction.bind(null, id, requirement.id)} requirement={requirement} submitLabel="Save requirement" /><form action={deleteRequirementAction.bind(null, id, requirement.id)} className="flex items-end"><ConfirmSubmitButton variant="destructive" confirmMessage={`Remove “${requirement.name}”? Existing packet snapshots will not change.`} pendingLabel="Removing…">Remove requirement</ConfirmSubmitButton></form></div></details></article>)}{!program.requirements.length && <div className="border bg-white p-8 text-center text-sm text-muted-foreground">No requirements are configured. Add the first requirement below.</div>}</div></section>
    <section className="mt-12"><SectionHeading index="03" title="Add requirement" /><div className="mt-5 border bg-white p-6"><RequirementForm action={addRequirementAction.bind(null, id)} submitLabel="Add requirement" /></div></section>
    <section className="mt-12"><div className="flex items-end justify-between gap-4"><SectionHeading index="04" title="Application templates" description="Import a real agency AcroForm or maintain a versioned generated application." /><Link href={`/admin/programs/${id}/templates/new`} className="shrink-0 border bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Create template</Link></div><div className="mt-5 border bg-white">{program.applicationTemplates.map((template) => <Link key={template.id} href={`/admin/templates/${template.id}`} className="grid gap-2 border-b p-5 last:border-b-0 sm:grid-cols-[1fr_auto_auto]"><span className="font-semibold">{template.name}</span><span className="text-sm text-muted-foreground">Version {template.version} · {template.templateType === "ACROFORM" ? "Agency PDF" : "Generated PDF"}</span><StatusBadge status={template.status} /></Link>)}{!program.applicationTemplates.length && <div className="p-6 text-sm text-muted-foreground">No application templates configured.</div>}</div></section>
    <section className="mt-12"><SectionHeading index="05" title="Submission destinations" description="Approved applications can be delivered by SMTP email or a provider-specific HTTPS API." /><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_1.2fr]"><div className="border bg-white">{program.submissionDestinations.map((destination) => <div key={destination.id} className="border-b p-5 last:border-b-0"><div className="font-semibold">{destination.name}</div><div className="mt-1 text-sm text-muted-foreground">{destination.type.replaceAll("_", " ")} · {destination.recipient ?? destination.endpoint}</div></div>)}{!program.submissionDestinations.length && <div className="p-6 text-sm text-muted-foreground">No delivery destination configured.</div>}</div><form action={addSubmissionDestinationAction.bind(null, id)} className="grid gap-4 border bg-white p-5 sm:grid-cols-2"><Field label="Destination name" name="name" required /><div className="space-y-2"><Label htmlFor="destination-type">Type</Label><select id="destination-type" name="type" className="h-9 w-full border bg-white px-3 text-sm"><option value="EMAIL">Email</option><option value="API">Provider API</option><option value="PORTAL_API">Portal API</option></select></div><Field label="Recipient email" name="recipient" /><Field label="HTTPS endpoint" name="endpoint" /><Field label="Bearer token" name="authToken" /><div className="flex items-end"><SubmitButton pendingLabel="Adding…">Add destination</SubmitButton></div></form></div></section></div>;
}

type Requirement = { name: string; category: string; description: string; isRequired: boolean; expirationPeriodDays: number | null; requiredFieldName: string | null; applicableHouseholdRules: string | null };
function RequirementForm({ action, requirement, submitLabel }: { action: (formData: FormData) => void | Promise<void>; requirement?: Requirement; submitLabel: string }) {
  return <form action={action} className="grid flex-1 gap-5 sm:grid-cols-2"><Field label="Requirement name" name="name" value={requirement?.name} required /><div className="space-y-2"><Label htmlFor={`category-${requirement?.name ?? "new"}`}>Category</Label><select id={`category-${requirement?.name ?? "new"}`} name="category" defaultValue={requirement?.category ?? "IDENTITY"} className="h-9 w-full border bg-white px-3 text-sm">{categories.map((category) => <option key={category}>{category}</option>)}</select></div><Area label="Description" name="description" value={requirement?.description} required /><Field label="Expiration period in days" name="expirationPeriodDays" type="number" value={requirement?.expirationPeriodDays?.toString()} /><Field label="Required extracted field" name="requiredFieldName" value={requirement?.requiredFieldName} /><div className="space-y-2"><Label htmlFor={`household-rule-${requirement?.name ?? "new"}`}>Conditional household rule</Label><select id={`household-rule-${requirement?.name ?? "new"}`} name="applicableHouseholdRules" defaultValue={requirement?.applicableHouseholdRules ?? ""} className="h-9 w-full border bg-white px-3 text-sm"><option value="">None</option><option value="HAS_ADDITIONAL_HOUSEHOLD_MEMBERS">Additional household members</option></select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isRequired" defaultChecked={requirement?.isRequired ?? true} /> Required</label><div className="flex justify-end sm:col-span-2"><SubmitButton pendingLabel="Saving…">{submitLabel}</SubmitButton></div></form>;
}
function Field({ label, name, value, type = "text", required = false }: { label: string; name: string; value?: string | null; type?: string; required?: boolean }) { const id = `${name}-${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${value ?? "new"}`; return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} name={name} defaultValue={value ?? ""} type={type} required={required} min={type === "number" ? 1 : undefined} /></div>; }
function Area({ label, name, value, required = false }: { label: string; name: string; value?: string | null; required?: boolean }) { const id = `${name}-${value?.slice(0, 8) ?? "new"}`; return <div className="space-y-2 sm:col-span-2"><Label htmlFor={id}>{label}</Label><Textarea id={id} name={name} defaultValue={value ?? ""} required={required} /></div>; }
