import Link from "next/link";
import { ArrowRight, FileText } from "lucide-react";
import { db } from "@/lib/db";
import { activateOrganizationContext, requireRole } from "@/lib/auth/session";
import { StatusBadge } from "@/components/status-badge";
import { formatDate } from "@/lib/format";

export default async function ReviewQueuePage() {
  const user = activateOrganizationContext(await requireRole(["REVIEWER", "CASEWORKER", "SUPERVISOR"]));
  const [packets, applications, documents] = await Promise.all([
    db.applicationPacket.findMany({ where: user.role === "CASEWORKER" ? { clientCase: { assignedCaseworkerId: user.id } } : { status: { not: "DRAFT" } }, include: { clientCase: true, housingProgram: true, fields: true }, orderBy: { generatedAt: "desc" } }),
    db.applicationDraft.findMany({ where: user.role === "CASEWORKER" ? { clientCase: { assignedCaseworkerId: user.id }, generatedAt: { not: null } } : { status: { in: ["SUBMITTED_FOR_REVIEW", "APPROVED", "RETURNED"] } }, include: { clientCase: true, template: { include: { housingProgram: true } }, fields: { include: { templateField: true } } }, orderBy: { updatedAt: "desc" } }),
    db.uploadedDocument.findMany({ where: { clientCase: user.role === "CASEWORKER" ? { assignedCaseworkerId: user.id } : undefined, OR: [{ processingStatus: "COMPLETED_WITH_REVIEW" }, { extractedFields: { some: { reviewStatus: { in: ["PENDING", "CONFLICTING"] } } } }] }, include: { clientCase: true, extractedFields: { select: { reviewStatus: true } } }, orderBy: { uploadedAt: "desc" }, take: 50 }),
  ]);
  return <div><p className="text-xs font-semibold uppercase tracking-[0.08em] text-primary">{user.role === "REVIEWER" ? "Reviewer workspace" : "Application status"}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.03em]">{user.role === "REVIEWER" ? "Review queue" : "Generated applications and review summaries"}</h1><p className="mt-2 text-sm text-muted-foreground">{user.role === "REVIEWER" ? "Review source evidence, completed application forms, and internal review snapshots from one queue." : "Track completed applications and the internal snapshots submitted for independent review."}</p>
    <section className="mt-9"><div className="border-b pb-4"><h2 className="text-xl font-semibold">Documents needing attention</h2><p className="mt-1 text-sm text-muted-foreground">Jump directly to uncertain, conflicting, or abstained extraction fields. Review the evidence rail before approving.</p></div><div className="divide-y">{documents.map((document) => { const pending = document.extractedFields.filter((field) => field.reviewStatus === "PENDING").length; const conflicts = document.extractedFields.filter((field) => field.reviewStatus === "CONFLICTING").length; return <Link data-row-link key={document.id} href={`/cases/${document.clientCaseId}/documents#document-${document.id}`} className="grid items-center gap-3 rounded-md px-3 py-4 md:grid-cols-[auto_1fr_1fr_180px_auto]"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-accent text-primary"><FileText className="h-4 w-4" /></span><div><div className="font-medium">{document.originalFilename}</div><div className="text-xs text-muted-foreground">{document.clientCase.preferredName ?? document.clientCase.legalName} · {document.clientCase.referenceNumber}</div></div><div className="text-sm text-muted-foreground">{pending} pending · {conflicts} conflicts</div><StatusBadge status={document.processingStatus} /><ArrowRight className="h-4 w-4" /></Link> })}{!documents.length && <div className="px-3 py-8 text-sm text-muted-foreground">No source documents need review.</div>}</div></section>
    <section className="mt-10"><div className="border-b pb-4"><h2 className="text-xl font-semibold">Completed housing applications</h2><p className="mt-1 text-sm text-muted-foreground">Template-backed application forms with their selected supporting documents.</p></div><div className="divide-y">{applications.map((draft) => <Link data-row-link key={draft.id} href={`/applications/${draft.id}/preview`} className="grid items-center gap-3 rounded-md px-3 py-4 md:grid-cols-[auto_1fr_1fr_160px_auto]"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-accent text-primary"><FileText className="h-4 w-4" /></span><div><div className="font-medium">{draft.clientCase.legalName}</div><div className="text-xs text-muted-foreground">{draft.clientCase.referenceNumber}-APP-V{Math.max(1, draft.generationVersion)}</div></div><div className="text-sm text-muted-foreground">{draft.template.name} · v{draft.templateVersion}</div><StatusBadge status={draft.status} /><ArrowRight className="h-4 w-4" /></Link>)}{!applications.length && <div className="px-3 py-8 text-sm text-muted-foreground">No completed applications are in this queue.</div>}</div></section>
    <section className="mt-10"><div className="border-b pb-4"><h2 className="text-xl font-semibold">Internal review summaries</h2><p className="mt-1 text-sm text-muted-foreground">Versioned case snapshots used for field and requirement review; these are not housing application forms.</p></div><div className="divide-y">{packets.map((packet) => <Link data-row-link key={packet.id} href={user.role === "REVIEWER" ? `/review/${packet.id}` : `/packets/${packet.id}`} className="grid items-center gap-3 rounded-md px-3 py-4 md:grid-cols-[130px_1fr_1fr_160px_100px_auto]"><div className="text-sm font-medium text-primary">{packet.referenceNumber}</div><div><div className="font-medium">{packet.clientCase.preferredName ?? packet.clientCase.legalName}</div><div className="mt-0.5 text-xs text-muted-foreground">Generated {formatDate(packet.generatedAt)}</div></div><div className="text-sm text-muted-foreground">{packet.housingProgram.name}</div><StatusBadge status={packet.status} /><div className="text-sm tabular-nums">{packet.fields.filter((field) => field.reviewStatus === "APPROVED").length}/{packet.fields.length} fields</div><ArrowRight className="h-4 w-4" /></Link>)}{!packets.length && <div className="px-3 py-8 text-sm text-muted-foreground">No internal review summaries are in this queue.</div>}</div></section>
  </div>;
}
