import { notFound } from "next/navigation";
import { CheckCircle2, FileText } from "lucide-react";
import { selectProgramAction } from "@/app/actions/cases";
import { db } from "@/lib/db";
import { activateOrganizationContext, canAccessCase, requireRole } from "@/lib/auth/session";
import { CaseHeader } from "@/features/cases/case-header";
import { SectionHeading } from "@/components/section-heading";
import { SubmitButton } from "@/components/submit-button";

export default async function ProgramPage({ params }: { params: Promise<{ id: string }> }) {
  const user = activateOrganizationContext(await requireRole(["CASEWORKER"])); const { id } = await params; if (!(await canAccessCase(user, id))) notFound();
  const [clientCase, programs] = await Promise.all([db.clientCase.findUnique({ where: { id } }), db.housingProgram.findMany({ where: { isActive: true }, include: { requirements: true, applicationTemplates: { where: { status: "ACTIVE" }, include: { fields: true } } }, orderBy: { name: "asc" } })]);
  if (!clientCase) notFound(); const action = selectProgramAction.bind(null, id);
  return <div><CaseHeader clientCase={clientCase} /><section className="mt-10"><SectionHeading title="Select a housing program" description="Programs and application templates shown here are fictional. Selection does not determine eligibility." /><form action={action} className="mt-5 space-y-4"><input type="hidden" name="recordVersion" value={clientCase.recordVersion} />{programs.map((program) => <label key={program.id} className={`block cursor-pointer rounded-lg border bg-white p-5 transition-[border-color,box-shadow] has-[:checked]:border-primary has-[:checked]:ring-2 has-[:checked]:ring-primary/10 ${clientCase.selectedProgramId === program.id ? "border-primary" : ""}`}><div className="flex items-start gap-4"><input type="radio" name="programId" value={program.id} defaultChecked={clientCase.selectedProgramId === program.id} className="mt-1 h-4 w-4 accent-[#244b6b]" /><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">{program.name}</h3><span className="rounded-full border border-sky-200 bg-sky-50 px-2 py-0.5 text-xs text-sky-800">Fictional program</span></div><p className="mt-1 text-sm text-muted-foreground">{program.organization}</p><p className="mt-3 max-w-3xl text-sm leading-6">{program.description}</p><div className="mt-5 grid gap-5 border-t pt-4 lg:grid-cols-2"><div><p className="text-xs font-medium text-muted-foreground">Required documents</p><div className="mt-2 space-y-2">{program.requirements.filter((item) => item.isRequired).map((requirement) => <div key={requirement.id} className="flex gap-2 text-sm"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{requirement.name}</div>)}</div></div><div><p className="text-xs font-medium text-muted-foreground">Available application templates</p><div className="mt-2 space-y-2">{program.applicationTemplates.map((template) => <div key={template.id} className="flex items-center gap-2 text-sm"><FileText className="h-4 w-4 text-primary" /><span>{template.name}</span><span className="text-xs text-muted-foreground">v{template.version} · {template.fields.length} fields</span></div>)}{!program.applicationTemplates.length && <p className="text-sm text-muted-foreground">No active template available.</p>}</div></div></div></div></div></label>)}<div className="flex justify-end"><SubmitButton pendingLabel="Saving selection…">Save program and continue</SubmitButton></div></form></section></div>;
}
