import { db } from "@/lib/db";
import { activateOrganizationContext, requireRole } from "@/lib/auth/session";
import { formatDate } from "@/lib/format";
import { approveCaseDeletionAction, cancelCaseDeletionAction, exportCaseDataAction, requestCaseDeletionAction, updateLegalHoldAction, updateRetentionPolicyAction, updateSignaturePolicyAction } from "@/app/actions/admin";
import { SubmitButton } from "@/components/submit-button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default async function DataGovernancePage() {
  const admin = activateOrganizationContext(await requireRole(["ADMIN"]));
  const [organization, cases, requests] = await Promise.all([
    db.organization.findUniqueOrThrow({ where: { id: admin.organizationId } }),
    db.clientCase.findMany({ select: { id: true, referenceNumber: true, legalName: true, retentionExpiresAt: true, legalHoldAt: true, legalHoldReason: true }, orderBy: { updatedAt: "desc" } }),
    db.dataLifecycleRequest.findMany({ include: { requestedBy: { select: { name: true } }, approvedBy: { select: { name: true } }, clientCase: { select: { referenceNumber: true } } }, orderBy: { requestedAt: "desc" }, take: 100 }),
  ]);
  return <div><p className="text-xs font-semibold uppercase tracking-[0.08em] text-primary">Administration</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.03em]">Data governance</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Manage retention, legal holds, encrypted exports, and two-person deletion approval. Audit records retain opaque case references after deletion.</p>
    <section className="mt-8 border bg-white p-5"><h2 className="text-xl font-semibold">Retention policy</h2><form action={updateRetentionPolicyAction} className="mt-4 grid gap-4 sm:grid-cols-[180px_180px_auto]"><div className="space-y-2"><Label htmlFor="retentionDays">Retain cases (days)</Label><Input id="retentionDays" name="retentionDays" type="number" min="30" max="36500" defaultValue={organization.retentionDays} required /></div><div className="space-y-2"><Label htmlFor="deletionGraceDays">Deletion grace (days)</Label><Input id="deletionGraceDays" name="deletionGraceDays" type="number" min="1" max="365" defaultValue={organization.deletionGraceDays} required /></div><div className="flex items-end"><SubmitButton pendingLabel="Saving…">Save policy</SubmitButton></div></form></section>
    <section className="mt-8 border bg-white p-5"><h2 className="text-xl font-semibold">Consent and signature policy</h2><p className="mt-2 text-sm text-muted-foreground">Changing this policy version invalidates the legal meaning of older unsigned forms. Signed records retain the exact version and content digest captured at signing.</p><form action={updateSignaturePolicyAction} className="mt-4 grid gap-4"><div className="space-y-2"><Label htmlFor="consentText">Document-release consent</Label><textarea id="consentText" name="consentText" rows={3} className="w-full rounded-md border bg-white px-3 py-2 text-sm" defaultValue={organization.consentText} required /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="signatureDisclaimer">Signature disclosure</Label><textarea id="signatureDisclaimer" name="signatureDisclaimer" rows={3} className="w-full rounded-md border bg-white px-3 py-2 text-sm" defaultValue={organization.signatureDisclaimer} required /></div><div className="grid content-start gap-4"><div className="space-y-2"><Label htmlFor="consentVersion">Policy version</Label><Input id="consentVersion" name="consentVersion" defaultValue={organization.consentVersion} pattern="[a-zA-Z0-9._-]+" required /></div><div className="space-y-2"><Label htmlFor="signaturePolicy">Signature method</Label><select id="signaturePolicy" name="signaturePolicy" defaultValue={organization.signaturePolicy} className="h-10 w-full rounded-md border bg-white px-3 text-sm"><option value="TYPED">Typed name</option><option value="TYPED_OR_DRAWN">Typed or externally drawn</option></select></div></div></div><div><SubmitButton pendingLabel="Saving…">Save consent and signature policy</SubmitButton></div></form></section>
    <section className="mt-10"><h2 className="text-xl font-semibold">Cases</h2><div className="mt-4 divide-y border bg-white">{cases.map((clientCase) => <article key={clientCase.id} className="grid gap-5 p-5 lg:grid-cols-[1fr_auto]"><div><div className="font-medium">{clientCase.legalName} <span className="text-sm font-normal text-muted-foreground">· {clientCase.referenceNumber}</span></div><div className="mt-1 text-xs text-muted-foreground">Retention expiry: {formatDate(clientCase.retentionExpiresAt)} · Legal hold: {clientCase.legalHoldAt ? `active since ${formatDate(clientCase.legalHoldAt)}` : "none"}</div><div className="mt-4 flex flex-wrap gap-2"><form action={exportCaseDataAction.bind(null, clientCase.id)}><SubmitButton size="sm" variant="outline" pendingLabel="Preparing…">Encrypted export</SubmitButton></form><form action={updateLegalHoldAction.bind(null, clientCase.id)} className="flex flex-wrap gap-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="enabled" defaultChecked={Boolean(clientCase.legalHoldAt)} /> Legal hold</label><Input name="reason" defaultValue={clientCase.legalHoldReason ?? ""} placeholder="Reason required when enabling" className="h-8 w-64" /><SubmitButton size="sm" variant="outline" pendingLabel="Saving…">Update hold</SubmitButton></form></div></div><form action={requestCaseDeletionAction.bind(null, clientCase.id)} className="flex items-end gap-2"><div className="space-y-2"><Label htmlFor={`delete-${clientCase.id}`}>Deletion reason</Label><Input id={`delete-${clientCase.id}`} name="reason" minLength={10} required disabled={Boolean(clientCase.legalHoldAt)} /></div><SubmitButton size="sm" variant="destructive" pendingLabel="Scheduling…" disabled={Boolean(clientCase.legalHoldAt)}>Request deletion</SubmitButton></form></article>)}</div></section>
    <section className="mt-10"><h2 className="text-xl font-semibold">Lifecycle requests</h2><div className="mt-4 divide-y border bg-white">{requests.length === 0 ? <p className="p-5 text-sm text-muted-foreground">No export or deletion requests.</p> : requests.map((request) => <div key={request.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_auto]"><div><div className="font-medium">{request.requestType} · {request.clientCase?.referenceNumber ?? request.clientCaseId ?? "deleted case"}</div><div className="mt-1 text-xs text-muted-foreground">{request.status} · requested {formatDate(request.requestedAt)} by {request.requestedBy?.name ?? "retention worker"}{request.approvedBy ? ` · approved by ${request.approvedBy.name}` : ""}{request.executeAfter ? ` · executes after ${formatDate(request.executeAfter)}` : ""}</div>{request.errorMessage && <p className="mt-2 text-sm text-destructive">{request.errorMessage}</p>}</div>{request.requestType === "DELETE" && ["PENDING", "APPROVED"].includes(request.status) && <div className="flex gap-2">{request.status === "PENDING" && request.requestedById !== admin.id && <form action={approveCaseDeletionAction.bind(null, request.id)}><SubmitButton size="sm" pendingLabel="Approving…">Approve</SubmitButton></form>}<form action={cancelCaseDeletionAction.bind(null, request.id)}><SubmitButton size="sm" variant="outline" pendingLabel="Canceling…">Cancel</SubmitButton></form></div>}</div>)}</div></section>
  </div>;
}
