import Link from "next/link";
import { notFound } from "next/navigation";
import { createAgencyFieldDefinitionAction, createDocumentProfileAction, createWorkflowDefinitionAction, deleteAgencyFieldDefinitionAction, importAgencyConfigurationAction } from "@/app/actions/agency-config";
import { SubmitButton, ConfirmSubmitButton } from "@/components/submit-button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { activateOrganizationContext, requireRole } from "@/lib/auth/session";
import { db } from "@/lib/db";

export default async function AgencyConfigurationPage() {
  const user = activateOrganizationContext(await requireRole(["ADMIN"]));
  const [fields, workflows, profiles] = await Promise.all([
    db.agencyFieldDefinition.findMany({ where: { organizationId: user.organizationId }, orderBy: { key: "asc" } }),
    db.workflowDefinition.findMany({ where: { organizationId: user.organizationId }, orderBy: { key: "asc" } }),
    db.documentProfile.findMany({ where: { organizationId: user.organizationId }, orderBy: { key: "asc" } }),
  ]);
  if (!user.organizationId) notFound();
  return <div><Link href="/admin" className="text-sm text-primary underline underline-offset-4">Back to administration</Link><p className="mt-10 text-xs font-semibold uppercase tracking-[0.08em] text-primary">Agency configuration</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.04em]">Define how your agency works</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Create custom fields, workflows, and document profiles without changing code. These definitions are private to your organization and can be exported for repeatable deployments.</p>
    <section className="mt-8 flex flex-wrap items-center gap-3 border bg-white p-5"><a href="/api/admin/agency-configuration/export" className="border px-4 py-2 text-sm font-medium">Export configuration</a><span className="text-xs text-muted-foreground">Export contains schema, workflows, and document profiles — never secrets or customer data.</span></section>
    <section className="mt-10"><h2 className="text-2xl font-semibold">Custom case fields</h2><div className="mt-4 divide-y border bg-white">{fields.map((field) => <div key={field.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><div className="font-medium">{field.label} <span className="text-xs text-muted-foreground">({field.key})</span></div><div className="text-xs text-muted-foreground">{field.fieldType} · {field.required ? "Required" : "Optional"}{field.helpText ? ` · ${field.helpText}` : ""}</div></div><form action={deleteAgencyFieldDefinitionAction.bind(null, field.id)}><ConfirmSubmitButton variant="outline" confirmMessage={`Deactivate ${field.label}? Existing case values are retained.`}>Remove</ConfirmSubmitButton></form></div>)}{!fields.length && <div className="p-5 text-sm text-muted-foreground">No custom fields yet.</div>}</div><form action={createAgencyFieldDefinitionAction} className="mt-4 grid gap-4 border bg-white p-5 sm:grid-cols-2"><Field name="key" label="Key" placeholder="household_language" /><Field name="label" label="Label" placeholder="Household language" /><div className="space-y-2"><Label htmlFor="fieldType">Type</Label><select id="fieldType" name="fieldType" className="h-9 w-full border bg-white px-3 text-sm"><option>TEXT</option><option>LONG_TEXT</option><option>DATE</option><option>NUMBER</option><option>CURRENCY</option><option>BOOLEAN</option><option>SELECT</option><option>MULTI_SELECT</option></select></div><Field name="helpText" label="Help text" placeholder="Explain what staff should enter" /><Field name="validationRules" label="Validation JSON" placeholder='{"minLength":2}' /><Field name="optionsJson" label="Options JSON" placeholder='["English","Spanish"]' /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="required" /> Required</label><div className="sm:col-span-2"><SubmitButton>Add custom field</SubmitButton></div></form></section>
    <section className="mt-10"><h2 className="text-2xl font-semibold">Workflow definitions</h2><div className="mt-4 divide-y border bg-white">{workflows.map((workflow) => <div key={workflow.id} className="p-4"><div className="font-medium">{workflow.name} <span className="text-xs text-muted-foreground">({workflow.key})</span></div><pre className="mt-2 overflow-auto text-xs text-muted-foreground">{workflow.stagesJson}</pre></div>)}{!workflows.length && <div className="p-5 text-sm text-muted-foreground">No custom workflows yet. Existing case statuses continue to work.</div>}</div><form action={createWorkflowDefinitionAction} className="mt-4 grid gap-4 border bg-white p-5"><Field name="key" label="Workflow key" placeholder="legal_aid_intake" /><Field name="name" label="Workflow name" placeholder="Legal aid intake" /><div className="space-y-2"><Label htmlFor="stagesJson">Stages JSON</Label><Textarea id="stagesJson" name="stagesJson" placeholder='[{"key":"intake","label":"Intake"},{"key":"review","label":"Review"}]' required /></div><SubmitButton>Add workflow</SubmitButton></form></section>
    <section className="mt-10"><h2 className="text-2xl font-semibold">Document profiles</h2><div className="mt-4 divide-y border bg-white">{profiles.map((profile) => <div key={profile.id} className="p-4"><div className="font-medium">{profile.name} <span className="text-xs text-muted-foreground">({profile.category})</span></div><div className="mt-1 text-xs text-muted-foreground">{profile.required ? "Required" : "Optional"} · {profile.extractionPrompt ? "Custom extraction guidance configured" : "Uses the local default prompt"}</div></div>)}{!profiles.length && <div className="p-5 text-sm text-muted-foreground">No custom document profiles yet.</div>}</div><form action={createDocumentProfileAction} className="mt-4 grid gap-4 border bg-white p-5 sm:grid-cols-2"><Field name="key" label="Profile key" placeholder="proof_of_residency" /><Field name="name" label="Profile name" placeholder="Proof of residency" /><Field name="category" label="Category" placeholder="RESIDENCY" /><Field name="validationRules" label="Validation JSON" placeholder='{"minConfidence":0.8}' /><div className="sm:col-span-2 space-y-2"><Label htmlFor="extractionPrompt">Local extraction guidance</Label><Textarea id="extractionPrompt" name="extractionPrompt" placeholder="Describe the fields this document normally contains and what evidence is required." /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="required" /> Required for this agency</label><div><SubmitButton>Add document profile</SubmitButton></div></form></section>
    <section className="mt-10"><h2 className="text-2xl font-semibold">Import configuration</h2><p className="mt-2 text-sm text-muted-foreground">Paste an export from another deployment. Existing definitions with the same keys are updated; customer cases and secrets are never imported.</p><form action={importAgencyConfigurationAction} className="mt-4 space-y-4 border bg-white p-5"><Textarea name="configuration" className="min-h-56 font-mono text-xs" placeholder="Paste hapb-agency-configuration/v1 JSON" required /><SubmitButton>Import configuration</SubmitButton></form></section>
  </div>;
}

function Field({ name, label, placeholder }: { name: string; label: string; placeholder: string }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} placeholder={placeholder} required={name === "key" || name === "label" || name === "name" || name === "category"} /></div>; }
