import Link from "next/link";
import { notFound } from "next/navigation";
import { Check, Download, FileStack, Send } from "lucide-react";
import { approveApplicationDraftAction, captureElectronicSignatureAction, deliverApprovedApplicationAction, generateApplicationAction, returnApplicationDraftAction, submitApplicationForReviewAction, updateDraftDocumentsAction } from "@/app/actions/applications";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { StatusBadge } from "@/components/status-badge";
import { SubmitButton } from "@/components/submit-button";
import { calculateDraftReadiness } from "@/lib/applications/mapping";
import { canAccessCase, requireUser } from "@/lib/auth/session";
import { db } from "@/lib/db";

export default async function ApplicationPreviewPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ generated?: string; error?: string }> }) {
  const user = await requireUser(); const { id } = await params; const { generated, error } = await searchParams;
  const draft = await db.applicationDraft.findUnique({
    where: { id },
    include: {
      clientCase: true,
      signature: true,
      template: { include: { housingProgram: { include: { submissionDestinations: { where: { enabled: true }, orderBy: { name: "asc" } } } } } },
      fields: { include: { templateField: true }, orderBy: { templateField: { displayOrder: "asc" } } },
      documents: { include: { uploadedDocument: { include: { extractedFields: true } } } },
      submissions: { include: { destination: true }, orderBy: { createdAt: "desc" } },
    },
  });
  if (!draft || !(await canAccessCase(user, draft.clientCaseId))) notFound();
  const readiness = calculateDraftReadiness(draft.fields.map((field) => ({ required: field.templateField.required, fieldType: field.templateField.fieldType, finalValue: field.finalValue, reviewState: field.reviewState, validationState: field.validationState })));
  const grouped = new Map<string, typeof draft.fields>(); for (const field of draft.fields) (grouped.get(field.templateField.section) ?? (grouped.set(field.templateField.section, []), grouped.get(field.templateField.section)!)).push(field);
  const generatedState = Boolean(draft.generatedAt);
  return <div><div className="no-print flex flex-wrap items-end justify-between gap-5 border-b pb-5"><div><Link href={`/applications/${id}`} className="text-sm font-medium text-primary underline underline-offset-4">Back to Prepare application</Link><p className="mt-4 text-xs font-semibold uppercase tracking-[0.08em] text-primary">Application form preview</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.03em]">{draft.template.name}</h1><p className="mt-2 text-sm text-muted-foreground">Template version {draft.templateVersion} · {draft.fields.length} fields · {readiness.blockingCount} unresolved</p></div><div className="flex flex-wrap items-center gap-2"><StatusBadge status={draft.status} />{user.role === "CASEWORKER" && !generatedState && <form action={generateApplicationAction.bind(null, id)}><SubmitButton disabled={!readiness.ready || !draft.signature} pendingLabel="Generating…"><FileStack /> Generate application</SubmitButton></form>}{generatedState && <><Button asChild variant="outline"><a href={`/api/applications/${id}/pdf`}><Download /> Completed application</a></Button><Button asChild variant="outline"><a href={`/api/applications/${id}/supporting-packet`}><Download /> Supporting packet</a></Button></>}{user.role === "CASEWORKER" && draft.status === "GENERATED" && <form action={submitApplicationForReviewAction.bind(null, id)}><SubmitButton pendingLabel="Submitting…"><Send /> Submit for review</SubmitButton></form>}</div></div>
    {error && <div role="alert" className="no-print mt-5 border border-red-300 bg-red-50 p-4 text-sm text-red-800">{error}</div>}
    {generated && <div role="status" className="no-print mt-5 rounded-md border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">Completed application version {draft.generationVersion} generated successfully.</div>}
    {!readiness.ready && <div role="alert" className="no-print mt-5 flex flex-wrap items-center justify-between gap-3 rounded-md border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><span>{readiness.blockingCount} required application field{readiness.blockingCount === 1 ? " needs" : "s need"} an answer before generation.</span><Button asChild size="sm"><Link href={`/applications/${id}/questions`}>Edit unresolved fields</Link></Button></div>}
    {user.role === "REVIEWER" && draft.status === "SUBMITTED_FOR_REVIEW" && <div className="no-print mt-5 rounded-lg border bg-white p-5"><h2 className="font-semibold">Reviewer decision</h2><p className="mt-1 text-sm text-muted-foreground">Review the completed application and selected supporting documents before recording a decision.</p><div className="mt-4 flex flex-wrap gap-3"><form action={returnApplicationDraftAction.bind(null, id)} className="flex flex-wrap gap-2"><Input name="note" required minLength={3} placeholder="Required correction" aria-label="Return application note" /><SubmitButton variant="outline" pendingLabel="Returning…">Return</SubmitButton></form><form action={approveApplicationDraftAction.bind(null, id)}><SubmitButton pendingLabel="Approving…"><Check /> Approve application</SubmitButton></form></div></div>}
    {user.role === "CASEWORKER" && !generatedState && <section className="no-print mt-6 border bg-white p-5"><h2 className="text-lg font-semibold">Electronic signature and consent</h2>{draft.signature ? <div className="mt-3 border-l-2 border-emerald-600 pl-4 text-sm"><div className="font-medium">Signed electronically by {draft.signature.signedName}</div><div className="mt-1 text-muted-foreground">{draft.signature.signedAt.toLocaleString()} · Document release consent recorded</div></div> : <form action={captureElectronicSignatureAction.bind(null, id)} className="mt-5 grid gap-4 sm:grid-cols-2"><div className="space-y-2"><label htmlFor="signedName" className="text-sm font-medium">Applicant’s typed legal name</label><Input id="signedName" name="signedName" required /></div><div className="space-y-2"><label htmlFor="signerEmail" className="text-sm font-medium">Applicant email (optional)</label><Input id="signerEmail" name="signerEmail" type="email" /></div><label className="flex items-start gap-3 text-sm sm:col-span-2"><input type="checkbox" name="attestation" required className="mt-1" /><span>I certify that the information in this application is complete and accurate to the best of my knowledge.</span></label><label className="flex items-start gap-3 text-sm sm:col-span-2"><input type="checkbox" name="documentConsent" required className="mt-1" /><span>I consent to the listed supporting documents being shared with this housing provider for this application.</span></label><div className="sm:col-span-2"><SubmitButton pendingLabel="Recording signature…">Sign and record consent</SubmitButton></div></form>}</section>}
    <article className="application-paper mx-auto mt-8 max-w-5xl border bg-white shadow-sm"><header className="border-b-8 border-primary bg-[#f5f7f8] px-6 py-8 sm:px-10"><p className="text-sm font-medium text-primary">{draft.template.housingProgram.name}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.03em]">{draft.template.name}</h2><div className="mt-4 flex flex-wrap gap-x-8 gap-y-2 text-xs text-muted-foreground"><span>Version {draft.templateVersion}</span><span>Application reference {draft.clientCase.referenceNumber}-APP-V{Math.max(1, draft.generationVersion)}</span><span>{draft.template.templateType === "ACROFORM" ? "Agency fillable PDF" : "Generated application form"}</span></div></header><div className="p-6 sm:p-10">{[...grouped.entries()].map(([section, fields]) => <ApplicationSection key={section} title={section} fields={fields} />)}<section className="mt-10 border-t pt-6"><h3 className="text-lg font-semibold">Applicant signature</h3><p className="mt-3 text-sm leading-6">I certify that the information in this application is complete and accurate to the best of my knowledge.</p><div className="mt-10 grid gap-8 sm:grid-cols-[1fr_180px]"><div><div className="min-h-6 border-b border-foreground">{draft.signature ? `/s/ ${draft.signature.signedName}` : ""}</div><p className="mt-2 text-xs text-muted-foreground">{draft.signature ? "Electronically signed" : "Applicant signature"}</p></div><div><div className="min-h-6 border-b border-foreground">{draft.signature?.signedAt.toLocaleDateString() ?? ""}</div><p className="mt-2 text-xs text-muted-foreground">Date</p></div></div></section></div></article>
    <section className="no-print mx-auto mt-8 max-w-5xl"><div className="border-b pb-4"><h2 className="text-xl font-semibold">Supporting packet documents</h2><p className="mt-1 text-sm text-muted-foreground">Only eligible, authorized documents selected here are included in the downloadable supporting packet.</p></div><form action={updateDraftDocumentsAction.bind(null, id)} className="mt-2 divide-y">{draft.documents.map((item) => { const eligible = item.authorized && item.uploadedDocument.processingStatus === "COMPLETED" && !item.uploadedDocument.extractedFields.some((field) => field.reviewStatus === "REJECTED"); return <label key={item.id} className="flex items-start gap-3 px-3 py-4 text-sm"><input type="checkbox" name="selectedDocument" value={item.uploadedDocumentId} defaultChecked={item.selected && eligible} disabled={!eligible || user.role !== "CASEWORKER"} className="mt-0.5 h-4 w-4 accent-[#244b6b]" /><span className="flex-1"><strong className="font-medium">{item.uploadedDocument.originalFilename}</strong><span className="mt-1 block text-xs text-muted-foreground">{item.uploadedDocument.documentCategory.replaceAll("_", " ")} · {eligible ? "Eligible for inclusion" : "Not eligible for inclusion"}</span></span></label>; })}{user.role === "CASEWORKER" && <div className="flex justify-end pt-4"><SubmitButton variant="outline" pendingLabel="Saving selection…">Update selection</SubmitButton></div>}</form></section>
    {user.role === "CASEWORKER" && draft.status === "APPROVED" && <section className="no-print mx-auto mt-8 max-w-5xl border bg-white p-5"><h2 className="text-xl font-semibold">Deliver approved application</h2><p className="mt-2 text-sm text-muted-foreground">Send the approved application and supporting packet through a configured provider destination. Every attempt is recorded.</p>{draft.template.housingProgram.submissionDestinations.length ? <form action={deliverApprovedApplicationAction.bind(null, id)} className="mt-5 flex flex-wrap items-end gap-3"><div className="min-w-72 space-y-2"><label htmlFor="destinationId" className="text-sm font-medium">Destination</label><select id="destinationId" name="destinationId" className="h-9 w-full border bg-white px-3 text-sm">{draft.template.housingProgram.submissionDestinations.map((destination) => <option key={destination.id} value={destination.id}>{destination.name} · {destination.type.replaceAll("_", " ")}</option>)}</select></div><SubmitButton pendingLabel="Delivering…"><Send /> Deliver application</SubmitButton></form> : <p className="mt-4 text-sm text-amber-800">An administrator must configure a submission destination for this program.</p>}<div className="mt-6 divide-y border-t">{draft.submissions.map((submission) => <div key={submission.id} className="grid gap-2 py-3 text-sm sm:grid-cols-[1fr_auto_auto]"><span>{submission.destination.name}</span><StatusBadge status={submission.status} /><span className="text-muted-foreground">{submission.submittedAt?.toLocaleString() ?? submission.errorMessage ?? "Pending"}</span></div>)}</div></section>}
  </div>;
}

function ApplicationSection({ title, fields }: { title: string; fields: { id: string; finalValue: string | null; templateField: { displayLabel: string; fieldType: string; required: boolean } }[] }) { return <section className="mt-9 first:mt-0"><h3 className="border-b pb-3 text-lg font-semibold">{title}</h3><div className="mt-4 grid gap-x-8 gap-y-6 sm:grid-cols-2">{fields.map((field) => field.templateField.fieldType === "HOUSEHOLD_TABLE" ? <HouseholdTable key={field.id} value={field.finalValue} /> : field.templateField.fieldType === "SIGNATURE_PLACEHOLDER" || field.templateField.fieldType === "SIGNATURE" ? null : <div key={field.id} className={field.templateField.fieldType === "MULTILINE_TEXT" ? "sm:col-span-2" : ""}><p className="text-xs font-medium text-muted-foreground">{field.templateField.displayLabel}</p><p className={`mt-1 min-h-6 border-b pb-2 text-sm ${field.finalValue ? "" : field.templateField.required ? "italic text-rose-700" : "italic text-muted-foreground"}`}>{field.finalValue || (field.templateField.required ? "Information required" : "Not provided")}</p></div>)}</div></section>; }
function HouseholdTable({ value }: { value: string | null }) { const rows = value ? JSON.parse(value) as { name: string; relationship: string; dateOfBirth: string | null; monthlyIncomeCents: number | null }[] : []; return <div className="overflow-x-auto sm:col-span-2"><table className="w-full min-w-[620px] border-collapse text-left text-sm"><thead><tr className="bg-secondary text-xs text-muted-foreground"><th className="border p-3 font-medium">Name</th><th className="border p-3 font-medium">Relationship</th><th className="border p-3 font-medium">Date of birth</th><th className="border p-3 font-medium">Monthly income</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.name}-${row.relationship}`}><td className="border p-3">{row.name}</td><td className="border p-3">{row.relationship}</td><td className="border p-3">{row.dateOfBirth ?? ""}</td><td className="border p-3">{row.monthlyIncomeCents === null ? "" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(row.monthlyIncomeCents / 100)}</td></tr>)}</tbody></table></div>; }
